### ISSUE TITLE
[BUG]: workspace_listing task find non-existing directories and fail.

### ISSUE THREAD

**Issue by dongwook-db** [databrickslabs/ucx#1328]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

UCX workspace_listing task faied with HTTP 400 error.  

```
databricks.sdk.errors.platform.BadRequest: 400 Bad Request 
Invalid request path
```
I added an additional exception handler on [listing.py ](https://github.com/databrickslabs/ucx/blob/main/src/databricks/labs/ucx/workspace_access/listing.py)to find error directory  and found _list_workspace_ trying to find non-exist directory path.

```
ERROR Path: /Users/AAA.kim@xx.ai/workflowspell: 400 Bad Request Invalid request path 
ERROR Path: /Users/AAA.kim@xx.ai/workflowgeo-search: 400 Bad Request Invalid request path
```

Actually _workflowspell_ and _geo-search_ does not exists under _AAA.kim@xx.ai_ directory.

![42dot_ucx](https://github.com/databrickslabs/ucx/assets/128602266/a56e7b62-b951-4277-8305-f827455dcbff)

### Cloud

AWS

### Operating System

macOS

### Version

latest via Databricks CLI

### Relevant log output

```shell
09:13:04 ERROR [databricks.labs.ucx] {MainThread} Execute `databricks workspace export //Applications/ucx/logs/assessment/run-865311439785318/workspace_listing.log` locally to troubleshoot with more details. 400 Bad Request
Invalid request path
09:13:04 DEBUG [databricks] {MainThread} Task crash details
Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/tasks.py", line 255, in run_task
    current_task.fn(cfg, workspace_client, sql_backend, installation)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/runtime.py", line 223, in workspace_listing
    crawler.snapshot()
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/workspace_access/generic.py", line 343, in snapshot
    return self._snapshot(self._try_fetch, self._crawl)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/crawlers.py", line 116, in _snapshot
    loaded_records = list(loader())
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/workspace_access/generic.py", line 331, in _crawl
    for obj in ws_listing.walk(self._start_path):
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/workspace_access/listing.py", line 93, in walk
    directories, others = future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/workspace_access/listing.py", line 63, in _list_and_analyze
    for is_directory, objects in grouped_iterator:
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/mixins/workspace.py", line 32, in list
    for object_info in parent_list(path, notebooks_modified_after=notebooks_modified_after):
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/service/workspace.py", line 2290, in list
    json = self._api.do('GET', '/api/2.0/workspace/list', query=query, headers=headers)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/core.py", line 130, in do
    response = retryable(self._perform)(method,
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/retries.py", line 54, in wrapper
    raise err
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/retries.py", line 33, in wrapper
    return func(*args, **kwargs)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/core.py", line 244, in _perform
    raise self._make_nicer_error(response=response, message=message) from None
databricks.sdk.errors.platform.BadRequest: 400 Bad Request
Invalid request path
```

**Comment by dongwook-db** [comment]
There is a special character(\x08) on the folder name. After rename a folder, issue has cleared.
```
ObjectInfo(created_at=None, language=None, modified_at=None, object_id=247755275477683, object_type=<ObjectType.DIRECTORY: 'DIRECTORY'>, path='/Users/seungmin.kim@42dot.ai/workflow/\x08spell', resource_id='247755275477683', size=None)
ObjectInfo(created_at=None, language=None, modified_at=None, object_id=385807149487872, object_type=<ObjectType.DIRECTORY: 'DIRECTORY'>, path='/Users/xxx/workflow/instant-search', resource_id='385807149487872', size=None)
ObjectInfo(created_at=None, language=None, modified_at=None, object_id=1045408928834013, object_type=<ObjectType.DIRECTORY: 'DIRECTORY'>, path='/Users/xxx/workflow/\x08geo-search', resource_id='1045408928834013', size=None)
```

**Comment by dongwook-db** [comment]
There is a special character(\x08) on the folder name. After rename a folder, issue has cleared.
```
ObjectInfo(created_at=None, language=None, modified_at=None, object_id=247755275477683, object_type=<ObjectType.DIRECTORY: 'DIRECTORY'>, path='/Users/xxx/workflow/\x08spell', resource_id='247755275477683', size=None)
ObjectInfo(created_at=None, language=None, modified_at=None, object_id=385807149487872, object_type=<ObjectType.DIRECTORY: 'DIRECTORY'>, path='/Users/xxx/workflow/instant-search', resource_id='385807149487872', size=None)
ObjectInfo(created_at=None, language=None, modified_at=None, object_id=1045408928834013, object_type=<ObjectType.DIRECTORY: 'DIRECTORY'>, path='/Users/xxx/workflow/\x08geo-search', resource_id='1045408928834013', size=None)
```

**Comment by dongwook-db** [comment]
There is a special character(\x08) on the folder name. After rename a folder, issue has cleared.
```
ObjectInfo(created_at=None, language=None, modified_at=None, object_id=247755275477683, object_type=<ObjectType.DIRECTORY: 'DIRECTORY'>, path='/Users/xxx/workflow/\x08spell', resource_id='247755275477683', size=None)
ObjectInfo(created_at=None, language=None, modified_at=None, object_id=385807149487872, object_type=<ObjectType.DIRECTORY: 'DIRECTORY'>, path='/Users/xxx/workflow/instant-search', resource_id='385807149487872', size=None)
ObjectInfo(created_at=None, language=None, modified_at=None, object_id=1045408928834013, object_type=<ObjectType.DIRECTORY: 'DIRECTORY'>, path='/Users/xxx/workflow/\x08geo-search', resource_id='1045408928834013', size=None)
```
