### ISSUE TITLE
[BUG]: ERROR [d.l.blueprint.parallel][installing_components_0] installing components task failed: timed out after 0:20:00:

### ISSUE THREAD

**Issue by gangvijay** [databrickslabs/ucx#1592]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am unable to install UCX and seeing below error.

12:44:13 ERROR [d.l.blueprint.parallel][installing_components_0] installing components task failed: timed out after 0:20:00: current status: PENDING: Traceback (most recent call last):
  File "C:\Users\nalajv1\.databricks\labs\ucx\state\venv\Lib\site-packages\databricks\labs\blueprint\parallel.py", line 140, in inner
    return func(*args, **kwargs), None

### Expected Behavior

I would like to install UCX and check whether we can use it to our UC migration.

### Cloud

AWS

### Operating System

Windows

### Version

latest via Databricks CLI

### Relevant log output

```shell
C:\Users\nalajv1>databricks labs install ucx
Using workspace profile: DEFAULT
12:23:46  INFO [src/databricks/labs/ucx/install] Installing UCX v0.22.0
12:23:47  WARN [src/databricks/labs/ucx/install] UCX workspace remote version not found: Path (/Applications/ucx/version.json) doesn't exist.
12:23:47  WARN [src/databricks/labs/ucx/install] Installed version is too old: Path (/Applications/ucx/version.json) doesn't exist.
12:23:47  INFO [src/databricks/labs/ucx/install] Installing UCX v0.22.0
12:23:47  INFO [src/databricks/labs/ucx/install][installing_components_0] Creating ucx schemas...
12:23:47  INFO [src/databricks/labs/ucx/install][installing_components_1] Creating dashboards...
12:44:13 ERROR [d.l.blueprint.parallel][installing_components_0] installing components task failed: timed out after 0:20:00: current status: PENDING: Traceback (most recent call last):
  File "C:\Users\nalajv1\.databricks\labs\ucx\state\venv\Lib\site-packages\databricks\labs\blueprint\parallel.py", line 140, in inner
    return func(*args, **kwargs), None
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nalajv1\.databricks\labs\ucx\lib\src\databricks\labs\ucx\install.py", line 490, in _create_database
    raise err
  File "C:\Users\nalajv1\.databricks\labs\ucx\lib\src\databricks\labs\ucx\install.py", line 479, in _create_database
    deploy_schema(self._sql_backend, self._config.inventory_database)
  File "C:\Users\nalajv1\.databricks\labs\ucx\lib\src\databricks\labs\ucx\install.py", line 81, in deploy_schema
    deployer.deploy_schema()
  File "C:\Users\nalajv1\.databricks\labs\ucx\state\venv\Lib\site-packages\databricks\labs\lsql\deployment.py", line 18, in deploy_schema
    self._sql_backend.execute(f"CREATE SCHEMA IF NOT EXISTS hive_metastore.{self._inventory_schema}")
  File "C:\Users\nalajv1\.databricks\labs\ucx\state\venv\Lib\site-packages\databricks\labs\lsql\backends.py", line 142, in execute
    self._sql.execute(sql, catalog=catalog, schema=schema)
  File "C:\Users\nalajv1\.databricks\labs\ucx\state\venv\Lib\site-packages\databricks\labs\lsql\core.py", line 268, in execute
    raise TimeoutError(msg)
TimeoutError: timed out after 0:20:00: current status: PENDING
12:44:13 ERROR [d.l.blueprint.parallel] More than half 'installing components' tasks failed: 0% results available (0/2). Took 0:20:25.274553
Traceback (most recent call last):
  File "C:\Users\nalajv1\.databricks\labs\ucx\lib\src\databricks\labs\ucx\install.py", line 686, in <module>
    workspace_installer.run()
  File "C:\Users\nalajv1\.databricks\labs\ucx\lib\src\databricks\labs\ucx\install.py", line 188, in run
    workspace_installation.run()
  File "C:\Users\nalajv1\.databricks\labs\ucx\lib\src\databricks\labs\ucx\install.py", line 466, in run
    Threads.strict("installing components", install_tasks)
  File "C:\Users\nalajv1\.databricks\labs\ucx\state\venv\Lib\site-packages\databricks\labs\blueprint\parallel.py", line 62, in strict
    raise errs[0]
  File "C:\Users\nalajv1\.databricks\labs\ucx\state\venv\Lib\site-packages\databricks\labs\blueprint\parallel.py", line 140, in inner
    return func(*args, **kwargs), None
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nalajv1\.databricks\labs\ucx\lib\src\databricks\labs\ucx\install.py", line 490, in _create_database
    raise err
  File "C:\Users\nalajv1\.databricks\labs\ucx\lib\src\databricks\labs\ucx\install.py", line 479, in _create_database
    deploy_schema(self._sql_backend, self._config.inventory_database)
  File "C:\Users\nalajv1\.databricks\labs\ucx\lib\src\databricks\labs\ucx\install.py", line 81, in deploy_schema
    deployer.deploy_schema()
  File "C:\Users\nalajv1\.databricks\labs\ucx\state\venv\Lib\site-packages\databricks\labs\lsql\deployment.py", line 18, in deploy_schema
    self._sql_backend.execute(f"CREATE SCHEMA IF NOT EXISTS hive_metastore.{self._inventory_schema}")
  File "C:\Users\nalajv1\.databricks\labs\ucx\state\venv\Lib\site-packages\databricks\labs\lsql\backends.py", line 142, in execute
    self._sql.execute(sql, catalog=catalog, schema=schema)
  File "C:\Users\nalajv1\.databricks\labs\ucx\state\venv\Lib\site-packages\databricks\labs\lsql\core.py", line 268, in execute
    raise TimeoutError(msg)
TimeoutError: timed out after 0:20:00: current status: PENDING
Error: installer: exit status 1
```

**Comment by nkvuong** [comment]
@gangvijay did you specify an existing sql warehouse, or for ucx to create a new one. either way, please check if you have a failed sql warehouse

**Comment by gangvijay** [comment]
Thanks for your reply. I had a issue with SQL warehouse and it is working now. Appreciated your time.!
