### ISSUE TITLE
[BUG]: Installation fails on AWS Sandbox

### ISSUE THREAD

**Issue by FastLee** [databrickslabs/ucx#1879]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Installation fails on AWS Sandbox

### Expected Behavior

Installation is expected to succeed.

### Steps To Reproduce

1. Run the installation from the cli (databricks labs install ucx)
2. Use all default values

### Cloud

AWS

### Operating System

macOS

### Version

latest via Databricks CLI

### Relevant log output

```shell
Traceback (most recent call last):
  File "/Users/liran.bareket/.databricks/labs/ucx/lib/src/databricks/labs/ucx/install.py", line 830, in <module>
    workspace_installer.run()
  File "/Users/liran.bareket/.databricks/labs/ucx/lib/src/databricks/labs/ucx/install.py", line 195, in run
    workspace_installation.run()
  File "/Users/liran.bareket/.databricks/labs/ucx/lib/src/databricks/labs/ucx/install.py", line 487, in run
    readme_url = self._workflows_installer.create_jobs()
  File "/Users/liran.bareket/.databricks/labs/ucx/lib/src/databricks/labs/ucx/installer/workflows.py", line 421, in create_jobs
    self._deploy_workflow(workflow_name, settings)
  File "/Users/liran.bareket/.databricks/labs/ucx/lib/src/databricks/labs/ucx/installer/workflows.py", line 527, in _deploy_workflow
    new_job = self._ws.jobs.create(**settings)
  File "/Users/liran.bareket/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/service/jobs.py", line 5257, in create
    res = self._api.do('POST', '/api/2.1/jobs/create', body=body, headers=headers)
  File "/Users/liran.bareket/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/core.py", line 130, in do
    response = retryable(self._perform)(method,
  File "/Users/liran.bareket/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/retries.py", line 54, in wrapper
    raise err
  File "/Users/liran.bareket/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/retries.py", line 33, in wrapper
    return func(*args, **kwargs)
  File "/Users/liran.bareket/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/core.py", line 241, in _perform
    raise self._make_nicer_error(response=response, **payload) from None
databricks.sdk.errors.platform.BadRequest: INVALID_PARAMETER_VALUE: Unknown node type id 
Error: installer: exit status 1
10:23:31 ERROR failed execution pid=84323 exit_code=1 error="installer: exit status 1"
```

**Comment by FastLee** [comment]
That happens when the user has an existing Cluster Policy
