### ISSUE TITLE
[BUG]:  Installation doesn't accept account ID

### ISSUE THREAD

**Issue by FastLee** [databrickslabs/ucx#1881]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Running the installer, I'm prompted to provide the account ID (twice) and the installation fails.
The account ID is valid and I'm properly logged in.

### Expected Behavior

The installation should accept the account id

### Cloud

AWS

### Operating System

macOS

### Version

latest via Databricks CLI

### Relevant log output

```shell
lease provide the Databricks account id: 2cffc3ba-0e89-463a-a7ec-8161b437db24
Traceback (most recent call last):
  File "/Users/liran.bareket/.databricks/labs/ucx/lib/src/databricks/labs/ucx/install.py", line 831, in <module>
    account_installer.join_collection(
  File "/Users/liran.bareket/.databricks/labs/ucx/lib/src/databricks/labs/ucx/install.py", line 695, in join_collection
    ids_to_workspace = self._get_workspace_info(current_workspace_id)
  File "/Users/liran.bareket/.databricks/labs/ucx/lib/src/databricks/labs/ucx/install.py", line 678, in _get_workspace_info
    workspace = account_client.workspaces.get(current_workspace_id)
  File "/Users/liran.bareket/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/service/provisioning.py", line 2626, in get
    res = self._api.do('GET',
  File "/Users/liran.bareket/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/core.py", line 130, in do
    response = retryable(self._perform)(method,
  File "/Users/liran.bareket/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/retries.py", line 54, in wrapper
    raise err
  File "/Users/liran.bareket/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/retries.py", line 33, in wrapper
    return func(*args, **kwargs)
  File "/Users/liran.bareket/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/core.py", line 241, in _perform
    raise self._make_nicer_error(response=response, **payload) from None
databricks.sdk.errors.platform.Unauthenticated: Cannot complete request; user is unauthenticated. Config: host=https://accounts.cloud.databricks.com, account_id=2cffc3ba-0e89-463a-a7ec-8161b437db24, token=***, auth_type=pat. Env: DATABRICKS_HOST, DATABRICKS_TOKEN
Error: installer: exit status 1
16:12:50 ERROR failed execution pid=23422 exit_code=1 error="installer: exit status 1"
```

**Comment by pritishpai** [comment]
After the workspace installation is done, the installer is failing while adding it to a collection at https://github.com/databrickslabs/ucx/blob/main/src/databricks/labs/ucx/install.py#L831.

For a workspace level install, we provide the workspace credentials and this is failing when it is trying to validate with account level credentials.
