### ISSUE TITLE
[BUG]: UCX is unable to create UCX schema

### ISSUE THREAD

**Issue by pepsicoanalytics** [databrickslabs/ucx#2168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

11:22:31  INFO [src/databricks/labs/ucx/install] Installing UCX v0.28.1
11:22:31  INFO [src/databricks/labs/ucx/install][installing_components_0] Creating ucx schemas...
11:22:31  INFO [src/databricks/labs/ucx/install][installing_components_1] Creating dashboards...
11:26:40 ERROR [d.l.blueprint.parallel][installing_components_0] installing components task failed: org.apache.hadoop.hive.ql.metadata.HiveException: MetaException(message:Got exception: org.apache.hadoop.fs.UnsupportedFileSystemException No FileSystem for scheme "dbfs"): Traceback (most recent call last):
  File "C:\Users\03344771\.databricks\labs\ucx\state\venv\Lib\site-packages\databricks\labs\blueprint\parallel.py", line 158, in inner
    return func(*args, **kwargs), None
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\03344771\.databricks\labs\ucx\lib\src\databricks\labs\ucx\install.py", line 513, in _create_database
    raise err
  File "C:\Users\03344771\.databricks\labs\ucx\lib\src\databricks\labs\ucx\install.py", line 502, in _create_database
    deploy_schema(self._sql_backend, self._config.inventory_database)
  File "C:\Users\03344771\.databricks\labs\ucx\lib\src\databricks\labs\ucx\install.py", line 88, in deploy_schema
    deployer.deploy_schema()
  File "C:\Users\03344771\.databricks\labs\ucx\state\venv\Lib\site-packages\databricks\labs\lsql\deployment.py", line 18, in deploy_schema
    self._sql_backend.execute(f"CREATE SCHEMA IF NOT EXISTS hive_metastore.{self._inventory_schema}")
  File "C:\Users\03344771\.databricks\labs\ucx\state\venv\Lib\site-packages\databricks\labs\lsql\backends.py", line 197, in execute
    self._sql.execute(sql, catalog=catalog, schema=schema)
  File "C:\Users\03344771\.databricks\labs\ucx\state\venv\Lib\site-packages\databricks\labs\lsql\core.py", line 266, in execute
    self._raise_if_needed(result_status)
  File "C:\Users\03344771\.databricks\labs\ucx\state\venv\Lib\site-packages\databricks\labs\lsql\core.py", line 480, in _raise_if_needed
    raise error_class(error_message)
databricks.sdk.errors.platform.BadRequest: org.apache.hadoop.hive.ql.metadata.HiveException: MetaException(message:Got exception: org.apache.hadoop.fs.UnsupportedFileSystemException No FileSystem for scheme "dbfs")
11:26:40 ERROR [d.l.blueprint.parallel] More than half 'installing components' tasks failed: 0% results available (0/2). Took 0:04:09.047404
Traceback (most recent call last):
  File "C:\Users\03344771\.databricks\labs\ucx\lib\src\databricks\labs\ucx\install.py", line 829, in <module>
    workspace_installer.run()
  File "C:\Users\03344771\.databricks\labs\ucx\lib\src\databricks\labs\ucx\install.py", line 198, in run
    workspace_installation.run()
  File "C:\Users\03344771\.databricks\labs\ucx\lib\src\databricks\labs\ucx\install.py", line 489, in run
    Threads.strict("installing components", install_tasks)
  File "C:\Users\03344771\.databricks\labs\ucx\state\venv\Lib\site-packages\databricks\labs\blueprint\parallel.py", line 62, in strict
    raise errs[0]
  File "C:\Users\03344771\.databricks\labs\ucx\state\venv\Lib\site-packages\databricks\labs\blueprint\parallel.py", line 158, in inner
    return func(*args, **kwargs), None
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\03344771\.databricks\labs\ucx\lib\src\databricks\labs\ucx\install.py", line 513, in _create_database
    raise err
  File "C:\Users\03344771\.databricks\labs\ucx\lib\src\databricks\labs\ucx\install.py", line 502, in _create_database
    deploy_schema(self._sql_backend, self._config.inventory_database)
  File "C:\Users\03344771\.databricks\labs\ucx\lib\src\databricks\labs\ucx\install.py", line 88, in deploy_schema
    deployer.deploy_schema()
  File "C:\Users\03344771\.databricks\labs\ucx\state\venv\Lib\site-packages\databricks\labs\lsql\deployment.py", line 18, in deploy_schema
    self._sql_backend.execute(f"CREATE SCHEMA IF NOT EXISTS hive_metastore.{self._inventory_schema}")
  File "C:\Users\03344771\.databricks\labs\ucx\state\venv\Lib\site-packages\databricks\labs\lsql\backends.py", line 197, in execute
    self._sql.execute(sql, catalog=catalog, schema=schema)
  File "C:\Users\03344771\.databricks\labs\ucx\state\venv\Lib\site-packages\databricks\labs\lsql\core.py", line 266, in execute
    self._raise_if_needed(result_status)
  File "C:\Users\03344771\.databricks\labs\ucx\state\venv\Lib\site-packages\databricks\labs\lsql\core.py", line 480, in _raise_if_needed
    raise error_class(error_message)
databricks.sdk.errors.platform.BadRequest: org.apache.hadoop.hive.ql.metadata.HiveException: MetaException(message:Got exception: org.apache.hadoop.fs.UnsupportedFileSystemException No FileSystem for scheme "dbfs")
Error: installer: exit status 1

### Expected Behavior

We have external hive metastore with postgresSQL. DB. UCX was able create DBSQL warehouse and able to connect to our external HMS, seems like unable to create ucx scheme/database.  

### Cloud

Azure

### Operating System

Windows

### Version

latest via Databricks CLI

**Comment by JCZuurmond** [comment]
Does the following help: https://community.databricks.com/t5/data-engineering/can-t-create-database-unsupportedfilesystemexception-no/td-p/20981?

**Comment by nikhilmish-db** [comment]
To circumvent this, we created a schema with a specified cloud storage location and configured UCX to generate assets in that location. Now, UCX will write to this schema(with a location). By prompting the script to write to that schema, we resolved this.
