### ISSUE TITLE
[BUG]: v0.30.0 installation fails when creating dashboards

### ISSUE THREAD

**Issue by FastLee** [databrickslabs/ucx#2268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When installing v0.30.0

### Expected Behavior

No exception is expected

### Cloud

AWS

### Operating System

macOS

### Version

latest via Databricks CLI

### Relevant log output

```shell
16:41:05 ERROR [d.l.blueprint.parallel][installing_dashboards_0] installing dashboards(PosixPath('/Users/liran.bareket/.databricks/labs/ucx/lib/src/databricks/labs/ucx/queries/assessment/azure'), parent_path='/Applications/ucx/dashboards') task failed: Dashboards.create_dashboard() got an unexpected keyword argument 'publish': Traceback (most recent call last):
  File "/Users/liran.bareket/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/labs/blueprint/parallel.py", line 158, in inner
    return func(*args, **kwargs), None
  File "/Users/liran.bareket/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/retries.py", line 54, in wrapper
    raise err
  File "/Users/liran.bareket/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/retries.py", line 33, in wrapper
    return func(*args, **kwargs)
  File "/Users/liran.bareket/.databricks/labs/ucx/lib/src/databricks/labs/ucx/install.py", line 607, in _create_dashboard
    dashboard = Dashboards(self._ws).create_dashboard(
TypeError: Dashboards.create_dashboard() got an unexpected keyword argument 'publish'
16:41:05 ERROR [d.l.blueprint.parallel][installing_dashboards_2] installing dashboards(PosixPath('/Users/liran.bareket/.databricks/labs/ucx/lib/src/databricks/labs/ucx/queries/assessment/interactive'), parent_path='/Applications/ucx/dashboards') task failed: Dashboards.create_dashboard() got an unexpected keyword argument 'publish': Traceback (most recent call last):
  File "/Users/liran.bareket/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/labs/blueprint/parallel.py", line 158, in inner
    return func(*args, **kwargs), None
  File "/Users/liran.bareket/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/retries.py", line 54, in wrapper
    raise err
  File "/Users/liran.bareket/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/retries.py", line 33, in wrapper
    return func(*args, **kwargs)
  File "/Users/liran.bareket/.databricks/labs/ucx/lib/src/databricks/labs/ucx/install.py", line 607, in _create_dashboard
    dashboard = Dashboards(self._ws).create_dashboard(
TypeError: Dashboards.create_dashboard() got an unexpected keyword argument 'publish'
16:41:05 ERROR [d.l.blueprint.parallel][installing_dashboards_4] installing dashboards(PosixPath('/Users/liran.bareket/.databricks/labs/ucx/lib/src/databricks/labs/ucx/queries/migration/main'), parent_path='/Applications/ucx/dashboards') task failed: Dashboards.create_dashboard() got an unexpected keyword argument 'publish': Traceback (most recent call last):
  File "/Users/liran.bareket/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/labs/blueprint/parallel.py", line 158, in inner
    return func(*args, **kwargs), None
  File "/Users/liran.bareket/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/retries.py", line 54, in wrapper
    raise err
  File "/Users/liran.bareket/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/retries.py", line 33, in wrapper
    return func(*args, **kwargs)
  File "/Users/liran.bareket/.databricks/labs/ucx/lib/src/databricks/labs/ucx/install.py", line 607, in _create_dashboard
    dashboard = Dashboards(self._ws).create_dashboard(
TypeError: Dashboards.create_dashboard() got an unexpected keyword argument 'publish'
16:41:05 ERROR [d.l.blueprint.parallel][installing_dashboards_1] installing dashboards(PosixPath('/Users/liran.bareket/.databricks/labs/ucx/lib/src/databricks/labs/ucx/queries/assessment/estimates'), parent_path='/Applications/ucx/dashboards') task failed: Dashboards.create_dashboard() got an unexpected keyword argument 'publish': Traceback (most recent call last):
  File "/Users/liran.bareket/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/labs/blueprint/parallel.py", line 158, in inner
    return func(*args, **kwargs), None
  File "/Users/liran.bareket/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/retries.py", line 54, in wrapper
    raise err
  File "/Users/liran.bareket/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/retries.py", line 33, in wrapper
    return func(*args, **kwargs)
  File "/Users/liran.bareket/.databricks/labs/ucx/lib/src/databricks/labs/ucx/install.py", line 607, in _create_dashboard
    dashboard = Dashboards(self._ws).create_dashboard(
TypeError: Dashboards.create_dashboard() got an unexpected keyword argument 'publish'
16:41:05 ERROR [d.l.blueprint.parallel][installing_dashboards_3] installing dashboards(PosixPath('/Users/liran.bareket/.databricks/labs/ucx/lib/src/databricks/labs/ucx/queries/assessment/main'), parent_path='/Applications/ucx/dashboards') task failed: Dashboards.create_dashboard() got an unexpected keyword argument 'publish': Traceback (most recent call last):
  File "/Users/liran.bareket/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/labs/blueprint/parallel.py", line 158, in inner
    return func(*args, **kwargs), None
  File "/Users/liran.bareket/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/retries.py", line 54, in wrapper
    raise err
  File "/Users/liran.bareket/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/retries.py", line 33, in wrapper
    return func(*args, **kwargs)
  File "/Users/liran.bareket/.databricks/labs/ucx/lib/src/databricks/labs/ucx/install.py", line 607, in _create_dashboard
    dashboard = Dashboards(self._ws).create_dashboard(
TypeError: Dashboards.create_dashboard() got an unexpected keyword argument 'publish'
16:41:05 FATAL [d.l.blueprint.parallel][installing_components_0] All 'installing dashboards' tasks failed!!!
16:41:05 ERROR [d.l.blueprint.parallel][installing_components_0] installing components task failed: Detected 5 failures: TypeError: Dashboards.create_dashboard() got an unexpected keyword argument 'publish': Traceback (most recent call last):
  File "/Users/liran.bareket/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/labs/blueprint/parallel.py", line 158, in inner
    return func(*args, **kwargs), None
  File "/Users/liran.bareket/.databricks/labs/ucx/lib/src/databricks/labs/ucx/install.py", line 515, in _create_database_and_dashboards
    Threads.strict("installing dashboards", list(self._get_create_dashboard_tasks()))
  File "/Users/liran.bareket/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/labs/blueprint/parallel.py", line 63, in strict
    raise ManyError(errs)
databricks.labs.blueprint.parallel.ManyError: Detected 5 failures: TypeError: Dashboards.create_dashboard() got an unexpected keyword argument 'publish'
16:41:10 ERROR [d.l.blueprint.parallel] More than half 'installing components' tasks failed: 0% results available (0/2). Took 0:00:16.667193
Traceback (most recent call last):
  File "/Users/liran.bareket/.databricks/labs/ucx/lib/src/databricks/labs/ucx/install.py", line 884, in <module>
    workspace_installer.run()
  File "/Users/liran.bareket/.databricks/labs/ucx/lib/src/databricks/labs/ucx/install.py", line 209, in run
    raise err
  File "/Users/liran.bareket/.databricks/labs/ucx/lib/src/databricks/labs/ucx/install.py", line 205, in run
    workspace_installation.run()
  File "/Users/liran.bareket/.databricks/labs/ucx/lib/src/databricks/labs/ucx/install.py", line 503, in run
    Threads.strict("installing components", install_tasks)
  File "/Users/liran.bareket/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/labs/blueprint/parallel.py", line 62, in strict
    raise errs[0]
  File "/Users/liran.bareket/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/labs/blueprint/parallel.py", line 158, in inner
    return func(*args, **kwargs), None
  File "/Users/liran.bareket/.databricks/labs/ucx/lib/src/databricks/labs/ucx/install.py", line 515, in _create_database_and_dashboards
    Threads.strict("installing dashboards", list(self._get_create_dashboard_tasks()))
  File "/Users/liran.bareket/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/labs/blueprint/parallel.py", line 63, in strict
    raise ManyError(errs)
databricks.labs.blueprint.parallel.ManyError: Detected 5 failures: TypeError: Dashboards.create_dashboard() got an unexpected keyword argument 'publish'
Error: installer: exit status 1
```
```

**Comment by nfx** [comment]
cannot reproduce on Databricks CLI v0.223.2

**Comment by louiscsq** [comment]
Sportsbet is experiencing the same issue. And they are on Databricks CLI v0.224.0 @nfx

**Comment by JCZuurmond** [comment]
Can not reproduce with a clean ucx install for `Databricks CLI v0.224.1`. 

@louiscsq : Are you upgrading or clean installing? Could you make sure you use the latest cli version. The patch release contains a fix for upgrading that might solve this issue

**Comment by JCZuurmond** [comment]
Could reproduce when upgrading ucx using the `Databricks cli v0.224.1`:

### Steps to reproduce
1. Install the latest Databricks cli version: download from https://github.com/databricks/ucx/releases
2. Install ucx (will work): `databricks labs install ucx`
3. Downgrade lsql `~/.databricks/labs/ucx/state/venv/bin/python3 -m pip install databricks-labs-lsql==0.7.2`
4. Upgrade ucx (will not work): `databricks labs upgrade ucx`

### Issue
`databricks labs upgrade <tool>` does not upgrade the dependencies if requirements are still satisfied thus patch releases are not upgraded

### Solution
Solve in the Databricks cli

### Workaround
Manually force reinstalling ucx and its dependencies:
1. `rm -rf ~/.databricks/labs/ucx`
2. `databricks labs install ucx`

Reinstall (requires to delete the remote ucx resources)
1. `databricks labs uninstall ucx`
2. `databricks labs install ucx`

NOTE: I am keeping this issue closed as it is an upstream issue
