### ISSUE TITLE
[BUG]: migrate-tables DBUtilsCore.mounts() is not whitelisted on class error

### ISSUE THREAD

**Issue by maruppel** [databrickslabs/ucx#2285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running migrate-tables workflow a Py4J Security Exception is thrown on all migrate tasks.

### Expected Behavior

The migrate-tables workflow succeeds migrating tables/views.

### Cloud

Azure

### Operating System

Windows

### Version

latest via Databricks CLI

### Relevant log output

```shell
16:46:22 DEBUG [databricks] {MainThread} Task crash details
Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/runtime.py", line 100, in trigger
    current_task(ctx)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/hive_metastore/workflows.py", line 29, in migrate_dbfs_root_delta_tables
    ctx.tables_migrator.migrate_tables(
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/hive_metastore/table_migrate.py", line 80, in migrate_tables
    all_principal_grants = None if acl_strategy is None else self._principal_grants.get_interactive_cluster_grants()
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/hive_metastore/grants.py", line 557, in get_interactive_cluster_grants
    mounts = list(self._mounts_crawler.snapshot())
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/hive_metastore/locations.py", line 252, in snapshot
    return self._snapshot(self._try_fetch, self._list_mounts)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/crawlers.py", line 116, in _snapshot
    loaded_records = list(loader())
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/hive_metastore/locations.py", line 247, in _list_mounts
    for mount_point, source, _ in self._dbutils.fs.mounts():
  File "/databricks/python_shell/dbruntime/dbutils.py", line 362, in f_with_exception_handling
    return f(*args, **kwargs)
  File "/databricks/python_shell/dbruntime/dbutils.py", line 497, in mounts
    self.print_return(self.dbcore.mounts()), MountInfo.create_from_jschema)
  File "/databricks/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1355, in __call__
    return_value = get_return_value(
  File "/databricks/spark/python/pyspark/errors/exceptions/captured.py", line 224, in deco
    return f(*a, **kw)
  File "/databricks/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 330, in get_return_value
    raise Py4JError(
py4j.protocol.Py4JError: An error occurred while calling o432.mounts. Trace:
py4j.security.Py4JSecurityException: Method public com.databricks.backend.daemon.dbutils.DBUtilsCore$Result com.databricks.backend.daemon.dbutils.DBUtilsCore.mounts() is not whitelisted on class class com.databricks.backend.daemon.dbutils.DBUtilsCore
	at py4j.security.WhitelistingPy4JSecurityManager.checkCall(WhitelistingPy4JSecurityManager.java:473)
	at py4j.Gateway.invoke(Gateway.java:305)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:199)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:119)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by ericvergnaud** [comment]
@maruppel although this issue occurs when running a ucx command, it seems to be an SDK error. Could you possibly report this issue in the SDK project https://github.com/databricks/databricks-sdk-py ?

**Comment by maruppel** [comment]
> The migrate-tables workflow succeeds migrating tables/views.

I created an issue in the SDK project as well. The UCX version is 0.28.2 and DB CLI is 0.221.1.

**Comment by maruppel** [comment]
> @maruppel although this issue occurs when running a ucx command, it seems to be an SDK error. Could you possibly report this issue in the SDK project https://github.com/databricks/databricks-sdk-py ?

I created an issue in the SDK project as well. The UCX version is 0.28.2 and DB CLI is 0.221.1.

**Comment by JCZuurmond** [comment]
@maruppel: I am re-investigating this issue. Could you chime in on this question in the other issue? https://github.com/databrickslabs/ucx/issues/2498#issuecomment-2315289547
