### ISSUE TITLE
[BUG]: Error Skipping Table With no DELTA_PATH

### ISSUE THREAD

**Issue by wesleyforti** [databrickslabs/ucx#2493]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Error when trying to skip table

```
Wesleys$ databricks labs ucx skip --schema XX --table YYY  -p myProfile
23:29:37  INFO [databricks.sdk] Using Databricks CLI authentication
23:29:37  INFO [d.labs.ucx] Running skip command
23:29:41  INFO [databricks.sdk] Using Databricks CLI authentication
23:29:47 ERROR [d.l.u.hive_metastore.mapping] Failed to apply skip marker for Table sales_silver.ncdt_web_promociones_v2: This Azure storage request is not authorized. The storage account's 'Firewalls and virtual networks' settings may be blocking access to storage services. Please verify your Azure storage credentials or firewall exception settings.: Traceback (most recent call last):
  File "/Users/wesley/.databricks/labs/ucx/lib/src/databricks/labs/ucx/hive_metastore/mapping.py", line 125, in skip_table_or_view
    self._sql_backend.execute(
  File "/Users/wesley/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/labs/lsql/backends.py", line 197, in execute
    self._sql.execute(sql, catalog=catalog, schema=schema)
  File "/Users/wesley/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/labs/lsql/core.py", line 255, in execute
    self._raise_if_needed(status)
  File "/Users/wesley/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/labs/lsql/core.py", line 492, in _raise_if_needed
    raise error_class(error_message)
databricks.sdk.errors.platform.BadRequest: This Azure storage request is not authorized. The storage account's 'Firewalls and virtual networks' settings may be blocking access to storage services. Please verify your Azure storage credentials or firewall exception settings.
```

### Expected Behavior

table skipped

### Steps To Reproduce

Try to migrate a table using ucx migrate-table task. Got an error.

then, 
I tried to skip it and got the error reported in the issue

### Cloud

Azure

### Operating System

macOS

### Version

latest via Databricks CLI

### Relevant log output

```shell
UCX migrate-table task logs

02:20:04 ERROR [databricks.labs.ucx] {MainThread} Execute `databricks workspace export //Applications/ucx/logs/migrate-tables/run-334174567997778-0/migrate_views.log` locally to troubleshoot with more details. [DELTA_PATH_DOES_NOT_EXIST] dbfs:/mnt/prod/inbound/XXX/YYYY doesn't exist, or is not a Delta table.;
ShowTableProperties upgraded_to, [key#41053, value#41052]
+- ResolvedTable com.databricks.sql.managedcatalog.UnityCatalogV2Proxy@61c3207b, Schema.table_name, DeltaTableV2(org.apache.spark.sql.SparkSession@72e987bc,dbfs:/mnt/prod/inbound/XXX/YYYY,Some(CatalogTable(
Catalog: hive_metastore
..
Owner: root
Created Time: Mon Jan 29 21:03:36 UTC 2024
Last Access: UNKNOWN
Created By: Spark 3.2.1
Type: EXTERNAL
Provider: delta
Table Properties: [delta.columnMapping.maxColumnId=26, delta.columnMapping.mode=name, delta.lastCommitTimestamp=1706562215000, delta.lastUpdateVersion=0, delta.minReaderVersion=2, delta.minWriterVersion=5]
Location: dbfs:/mnt/prod/inbound/XXX/YYYY
Serde Library: org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe
InputFormat: org.apache.hadoop.mapred.SequenceFileInputFormat
OutputFormat: org.apache.hadoop.hive.ql.io.HiveSequenceFileOutputFormat
Partition Provider: Catalog
Schema: root



JVM stacktrace:
org.apache.spark.sql.catalyst.ExtendedAnalysisException
	at com.databricks.sql.transaction.tahoe.DeltaErrorsBase.pathNotExistsException(DeltaErrors.scala:841)
	at com.databricks.sql.transaction.tahoe.DeltaErrorsBase.pathNotExistsException$(DeltaErrors.scala:840)
	at com.databricks.sql.transaction.tahoe.DeltaErrors$.pathNotExistsException(DeltaErrors.scala:3528)
	at com.databricks.sql.transaction.tahoe.DeltaUnsupportedOperationsCheck.$anonfun$apply$1(DeltaUnsupportedOperationsCheck.scala:128)
	at com.databricks.sql.transaction.tahoe.DeltaUnsupportedOperationsCheck.$anonfun$apply$1$adapted(DeltaUnsupportedOperationsCheck.scala:67)
	at org.apache.spark.sql.catalyst.trees.TreeNode.foreach(TreeNode.scala:277)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$foreach$1(TreeNode.scala:278)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$foreach$1$adapted(TreeNode.scala:278)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at org.apache.spark.sql.catalyst.trees.TreeNode.foreach(TreeNode.scala:278)
	at com.databricks.sql.transaction.tahoe.DeltaUnsupportedOperationsCheck.apply(DeltaUnsupportedOperationsCheck.scala:67)
	at com.databricks.sql.transaction.tahoe.DeltaUnsupportedOperationsCheck.apply(DeltaUnsupportedOperationsCheck.scala:43)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$52(CheckAnalysis.scala:852)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$52$adapted(CheckAnalysis.scala:852)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis0(CheckAnalysis.scala:852)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis0$(CheckAnalysis.scala:224)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis0(Analyzer.scala:348)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis$1(CheckAnalysis.scala:212)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:94)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis(CheckAnalysis.scala:180)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis$(CheckAnalysis.scala:180)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis(Analyzer.scala:348)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$executeAndCheck$2(Analyzer.scala:403)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:168)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$executeAndCheck$1(Analyzer.scala:403)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.markInAnalyzer(AnalysisHelper.scala:443)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:400)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$analyzed$1(QueryExecution.scala:261)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:94)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:427)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$5(QueryExecution.scala:611)
	at org.apache.spark.sql.execution.SQLExecution$.withExecutionPhase(SQLExecution.scala:143)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$4(QueryExecution.scala:611)
	at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:1164)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$2(QueryExecution.scala:610)
	at com.databricks.util.LexicalThreadLocal$Handle.runWith(LexicalThreadLocal.scala:63)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:606)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:1180)
	at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:606)
	at org.apache.spark.sql.execution.QueryExecution.analyzed$lzycompute(QueryExecution.scala:255)
	at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:254)
	at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:236)
	at org.apache.spark.sql.Dataset$.$anonfun$ofRows$2(Dataset.scala:130)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:1180)
	at org.apache.spark.sql.SparkSession.$anonfun$withActiveAndFrameProfiler$1(SparkSession.scala:1187)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:94)
	at org.apache.spark.sql.SparkSession.withActiveAndFrameProfiler(SparkSession.scala:1187)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:122)
	at org.apache.spark.sql.SparkSession.$anonfun$sql$4(SparkSession.scala:959)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:1180)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:947)
	at org.apache.spark.sql.connect.planner.SparkConnectPlanner.executeSQL(SparkConnectPlanner.scala:2939)
	at org.apache.spark.sql.connect.planner.SparkConnectPlanner.handleSqlCommand(SparkConnectPlanner.scala:2781)
	at org.apache.spark.sql.connect.planner.SparkConnectPlanner.process(SparkConnectPlanner.scala:2722)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.handleCommand(ExecuteThreadRunner.scala:320)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.$anonfun$executeInternal$1(ExecuteThreadRunner.scala:242)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.$anonfun$executeInternal$1$adapted(ExecuteThreadRunner.scala:178)
	at org.apache.spark.sql.connect.service.SessionHolder.$anonfun$withSession$2(SessionHolder.scala:340)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:1180)
	at org.apache.spark.sql.connect.service.SessionHolder.$anonfun$withSession$1(SessionHolder.scala:340)
	at org.apache.spark.JobArtifactSet$.withActiveJobArtifactState(JobArtifactSet.scala:97)
	at org.apache.spark.sql.artifact.ArtifactManager.$anonfun$withResources$1(ArtifactManager.scala:84)
	at org.apache.spark.util.Utils$.withContextClassLoader(Utils.scala:235)
	at org.apache.spark.sql.artifact.ArtifactManager.withResources(ArtifactManager.scala:83)
	at org.apache.spark.sql.connect.service.SessionHolder.withSession(SessionHolder.scala:339)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.executeInternal(ExecuteThreadRunner.scala:178)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.org$apache$spark$sql$connect$execution$ExecuteThreadRunner$$execute(ExecuteThreadRunner.scala:128)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner$ExecutionThread.$anonfun$run$2(ExecuteThreadRunner.scala:527)
	at com.databricks.unity.UCSEphemeralState$Handle.runWith(UCSEphemeralState.scala:45)
	at com.databricks.unity.HandleImpl.runWith(UCSHandle.scala:103)
	at com.databricks.unity.HandleImpl.$anonfun$runWithAndClose$1(UCSHandle.scala:108)
	at scala.util.Using$.resource(Using.scala:269)
	at com.databricks.unity.HandleImpl.runWithAndClose(UCSHandle.scala:107)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner$ExecutionThread.run(ExecuteThreadRunner.scala:526)
02:20:04 DEBUG [databricks] {MainThread} Task crash details
Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/databricks/labs/ucx/runtime.py", line 100, in trigger
    current_task(ctx)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/databricks/labs/ucx/hive_metastore/workflows.py", line 63, in migrate_views
    ctx.tables_migrator.migrate_tables(
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/databricks/labs/ucx/hive_metastore/table_migrate.py", line 96, in migrate_tables
    return self._migrate_views(acl_strategy, all_grants_to_migrate, all_migrated_groups, all_principal_grants)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/databricks/labs/ucx/hive_metastore/table_migrate.py", line 134, in _migrate_views
    sequencer = ViewsMigrationSequencer(tables_to_migrate, self.index_full_refresh())
                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/databricks/labs/ucx/hive_metastore/table_migrate.py", line 75, in index_full_refresh
    return self._migration_status_refresher.index()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/databricks/labs/ucx/hive_metastore/migration_status.py", line 81, in index
    return MigrationIndex(list(self.snapshot()))
                               ^^^^^^^^^^^^^^^
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/databricks/labs/ucx/hive_metastore/migration_status.py", line 78, in snapshot
    return self._snapshot(self._try_fetch, self._crawl)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/databricks/labs/ucx/framework/crawlers.py", line 118, in _snapshot
    loaded_records = list(loader())
                     ^^^^^^^^^^^^^^
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/databricks/labs/ucx/hive_metastore/migration_status.py", line 129, in _crawl
    if table.key in reverse_seen and self.is_migrated(src_schema, src_table):
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/databricks/labs/ucx/hive_metastore/migration_status.py", line 106, in is_migrated
    results = self._backend.fetch(
              ^^^^^^^^^^^^^^^^^^^^
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/databricks/labs/lsql/backends.py", line 256, in fetch
    raise self._api_error_from_message(error_message) from None
databricks.sdk.errors.platform.Unknown: [DELTA_PATH_DOES_NOT_EXIST] dbfs:/mnt/prod/inbound/XXX/YYYY doesn't exist, or is not a Delta table.;
ShowTableProperties upgraded_to, [key#41053, value#41052]
```

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by JCZuurmond** [comment]
@wesleyforti : The table can probably not be migrated for the same reason that it can not be skipped. It looks like the table is invalid because the delta path does not exist. The other tables should still be migrated by the `migrate-tables` task, that it fails is not a problem. Please add more information if you think this is a problem.
