### ISSUE TITLE
[BUG]: installation fails because of dashboards in v0.33.0

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#2496]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

fails

### Expected Behavior

not fails

### Steps To Reproduce

`databricks labs install ucx`

### Cloud

AWS

### Operating System

macOS

### Version

latest via Databricks CLI

### Relevant log output

```shell
10:46:39  INFO [d.l.ucx.install][installing_dashboards_5] Creating dashboard in /Users/serge.smertin/.databricks/labs/ucx/lib/src/databricks/labs/ucx/queries/migration/main...
10:46:40 ERROR [d.l.blueprint.parallel][installing_dashboards_0] installing dashboards(PosixPath('/Users/serge.smertin/.databricks/labs/ucx/lib/src/databricks/labs/ucx/queries/assessment/azure'), parent_path='/Applications/ucx/dashboards') task failed: validation failed: [resource name must be unique; found duplicates: [05_0_azure_service_principals]]: Traceback (most recent call last):
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/labs/blueprint/parallel.py", line 158, in inner
    return func(*args, **kwargs), None
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/retries.py", line 54, in wrapper
    raise err
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/retries.py", line 33, in wrapper
    return func(*args, **kwargs)
  File "/Users/serge.smertin/.databricks/labs/ucx/lib/src/databricks/labs/ucx/install.py", line 622, in _create_dashboard
    dashboard = Dashboards(self._ws).create_dashboard(
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/labs/lsql/dashboards.py", line 946, in create_dashboard
    sdk_dashboard = self._ws.lakeview.update(
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/service/dashboards.py", line 1129, in update
    res = self._api.do('PATCH',
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/core.py", line 153, in do
    response = retryable(self._perform)(method,
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/retries.py", line 54, in wrapper
    raise err
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/retries.py", line 33, in wrapper
    return func(*args, **kwargs)
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/core.py", line 264, in _perform
    raise self._make_nicer_error(response=response, **payload) from None
databricks.sdk.errors.platform.InvalidParameterValue: validation failed: [resource name must be unique; found duplicates: [05_0_azure_service_principals]]
10:46:40 ERROR [d.l.blueprint.parallel][installing_dashboards_4] installing dashboards(PosixPath('/Users/serge.smertin/.databricks/labs/ucx/lib/src/databricks/labs/ucx/queries/migration/groups'), parent_path='/Applications/ucx/dashboards') task failed: validation failed: [resource name must be unique; found duplicates: [01_1_group_migration_failures]]: Traceback (most recent call last):
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/labs/blueprint/parallel.py", line 158, in inner
    return func(*args, **kwargs), None
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/retries.py", line 54, in wrapper
    raise err
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/retries.py", line 33, in wrapper
    return func(*args, **kwargs)
  File "/Users/serge.smertin/.databricks/labs/ucx/lib/src/databricks/labs/ucx/install.py", line 622, in _create_dashboard
    dashboard = Dashboards(self._ws).create_dashboard(
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/labs/lsql/dashboards.py", line 946, in create_dashboard
    sdk_dashboard = self._ws.lakeview.update(
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/service/dashboards.py", line 1129, in update
    res = self._api.do('PATCH',
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/core.py", line 153, in do
    response = retryable(self._perform)(method,
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/retries.py", line 54, in wrapper
    raise err
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/retries.py", line 33, in wrapper
    return func(*args, **kwargs)
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/core.py", line 264, in _perform
    raise self._make_nicer_error(response=response, **payload) from None
databricks.sdk.errors.platform.InvalidParameterValue: validation failed: [resource name must be unique; found duplicates: [01_1_group_migration_failures]]
10:46:40 ERROR [d.l.blueprint.parallel][installing_dashboards_5] installing dashboards(PosixPath('/Users/serge.smertin/.databricks/labs/ucx/lib/src/databricks/labs/ucx/queries/migration/main'), parent_path='/Applications/ucx/dashboards') task failed: validation failed: [resource name must be unique; found duplicates: [01_1_data_object_migration_summary, 02_1_code_compatibility_problems, 02_1_data_reconciliation_summary, 03_1_data_reconciliation_status, 04_1_remaining_hms_tables]]: Traceback (most recent call last):
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/labs/blueprint/parallel.py", line 158, in inner
    return func(*args, **kwargs), None
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/retries.py", line 54, in wrapper
    raise err
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/retries.py", line 33, in wrapper
    return func(*args, **kwargs)
  File "/Users/serge.smertin/.databricks/labs/ucx/lib/src/databricks/labs/ucx/install.py", line 622, in _create_dashboard
    dashboard = Dashboards(self._ws).create_dashboard(
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/labs/lsql/dashboards.py", line 946, in create_dashboard
    sdk_dashboard = self._ws.lakeview.update(
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/service/dashboards.py", line 1129, in update
    res = self._api.do('PATCH',
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/core.py", line 153, in do
    response = retryable(self._perform)(method,
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/retries.py", line 54, in wrapper
    raise err
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/retries.py", line 33, in wrapper
    return func(*args, **kwargs)
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/core.py", line 264, in _perform
    raise self._make_nicer_error(response=response, **payload) from None
databricks.sdk.errors.platform.InvalidParameterValue: validation failed: [resource name must be unique; found duplicates: [01_1_data_object_migration_summary, 02_1_code_compatibility_problems, 02_1_data_reconciliation_summary, 03_1_data_reconciliation_status, 04_1_remaining_hms_tables]]
10:46:40 ERROR [d.l.blueprint.parallel][installing_dashboards_2] installing dashboards(PosixPath('/Users/serge.smertin/.databricks/labs/ucx/lib/src/databricks/labs/ucx/queries/assessment/interactive'), parent_path='/Applications/ucx/dashboards') task failed: validation failed: [resource name must be unique; found duplicates: [01_0_compute_access_mode_limitation_summary, 03_0_cluster_summary]]: Traceback (most recent call last):
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/labs/blueprint/parallel.py", line 158, in inner
    return func(*args, **kwargs), None
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/retries.py", line 54, in wrapper
    raise err
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/retries.py", line 33, in wrapper
    return func(*args, **kwargs)
  File "/Users/serge.smertin/.databricks/labs/ucx/lib/src/databricks/labs/ucx/install.py", line 622, in _create_dashboard
    dashboard = Dashboards(self._ws).create_dashboard(
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/labs/lsql/dashboards.py", line 946, in create_dashboard
    sdk_dashboard = self._ws.lakeview.update(
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/service/dashboards.py", line 1129, in update
    res = self._api.do('PATCH',
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/core.py", line 153, in do
    response = retryable(self._perform)(method,
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/retries.py", line 54, in wrapper
    raise err
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/retries.py", line 33, in wrapper
    return func(*args, **kwargs)
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/core.py", line 264, in _perform
    raise self._make_nicer_error(response=response, **payload) from None
databricks.sdk.errors.platform.InvalidParameterValue: validation failed: [resource name must be unique; found duplicates: [01_0_compute_access_mode_limitation_summary, 03_0_cluster_summary]]
10:46:40 ERROR [d.l.blueprint.parallel][installing_dashboards_1] installing dashboards(PosixPath('/Users/serge.smertin/.databricks/labs/ucx/lib/src/databricks/labs/ucx/queries/assessment/estimates'), parent_path='/Applications/ucx/dashboards') task failed: validation failed: [resource name must be unique; found duplicates: [00_4_is_incompatible_submit_run_detected, 01_2_group_migration, 01_5_group_migration_complexity, 02_2_uc_data_modeling, 02_5_uc_data_modeling_complexity, 03_2_data_migration_summary, 03_5_data_migration_complexity, 04_1_data_migration_effort]]: Traceback (most recent call last):
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/labs/blueprint/parallel.py", line 158, in inner
    return func(*args, **kwargs), None
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/retries.py", line 54, in wrapper
    raise err
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/retries.py", line 33, in wrapper
    return func(*args, **kwargs)
  File "/Users/serge.smertin/.databricks/labs/ucx/lib/src/databricks/labs/ucx/install.py", line 622, in _create_dashboard
    dashboard = Dashboards(self._ws).create_dashboard(
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/labs/lsql/dashboards.py", line 946, in create_dashboard
    sdk_dashboard = self._ws.lakeview.update(
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/service/dashboards.py", line 1129, in update
    res = self._api.do('PATCH',
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/core.py", line 153, in do
    response = retryable(self._perform)(method,
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/retries.py", line 54, in wrapper
    raise err
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/retries.py", line 33, in wrapper
    return func(*args, **kwargs)
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/core.py", line 264, in _perform
    raise self._make_nicer_error(response=response, **payload) from None
databricks.sdk.errors.platform.InvalidParameterValue: validation failed: [resource name must be unique; found duplicates: [00_4_is_incompatible_submit_run_detected, 01_2_group_migration, 01_5_group_migration_complexity, 02_2_uc_data_modeling, 02_5_uc_data_modeling_complexity, 03_2_data_migration_summary, 03_5_data_migration_complexity, 04_1_data_migration_effort]]
10:46:40 ERROR [d.l.blueprint.parallel][installing_dashboards_3] installing dashboards(PosixPath('/Users/serge.smertin/.databricks/labs/ucx/lib/src/databricks/labs/ucx/queries/assessment/main'), parent_path='/Applications/ucx/dashboards') task failed: validation failed: [resource name must be unique; found duplicates: [00_1_count_table_failures, 00_2_count_total_databases, 00_3_count_total_tables, 00_4_count_total_views, 00_5_count_external_locations, 00_6_count_total_udfs, 00_7_count_storage_credentials, 01_0_compatibility, 01_1_count_jobs, 01_2_count_table_by_storage, 01_3_count_table_by_type_location_format, 05_0_object_readiness, 05_2_assessment_summary, 10_0_database_summary, 10_1_all_tables, 10_2_all_udfs, 15_0_external_locations, 15_3_mount_points, 20_0_clusters, 20_1_cluster_policies, 30_3_job_details, 30_3_jobs, 30_4_submit_runs, 30_5_submit_runs, 40_0_grants, 40_1_pipelines, 40_2_global_init_scripts, 40_3_logs]]: Traceback (most recent call last):
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/labs/blueprint/parallel.py", line 158, in inner
    return func(*args, **kwargs), None
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/retries.py", line 54, in wrapper
    raise err
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/retries.py", line 33, in wrapper
    return func(*args, **kwargs)
  File "/Users/serge.smertin/.databricks/labs/ucx/lib/src/databricks/labs/ucx/install.py", line 622, in _create_dashboard
    dashboard = Dashboards(self._ws).create_dashboard(
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/labs/lsql/dashboards.py", line 946, in create_dashboard
    sdk_dashboard = self._ws.lakeview.update(
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/service/dashboards.py", line 1129, in update
    res = self._api.do('PATCH',
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/core.py", line 153, in do
    response = retryable(self._perform)(method,
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/retries.py", line 54, in wrapper
    raise err
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/retries.py", line 33, in wrapper
    return func(*args, **kwargs)
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/core.py", line 264, in _perform
    raise self._make_nicer_error(response=response, **payload) from None
databricks.sdk.errors.platform.InvalidParameterValue: validation failed: [resource name must be unique; found duplicates: [00_1_count_table_failures, 00_2_count_total_databases, 00_3_count_total_tables, 00_4_count_total_views, 00_5_count_external_locations, 00_6_count_total_udfs, 00_7_count_storage_credentials, 01_0_compatibility, 01_1_count_jobs, 01_2_count_table_by_storage, 01_3_count_table_by_type_location_format, 05_0_object_readiness, 05_2_assessment_summary, 10_0_database_summary, 10_1_all_tables, 10_2_all_udfs, 15_0_external_locations, 15_3_mount_points, 20_0_clusters, 20_1_cluster_policies, 30_3_job_details, 30_3_jobs, 30_4_submit_runs, 30_5_submit_runs, 40_0_grants, 40_1_pipelines, 40_2_global_init_scripts, 40_3_logs]]
10:46:40 FATAL [d.l.blueprint.parallel][installing_components_0] All 'installing dashboards' tasks failed!!!
10:46:40 ERROR [d.l.blueprint.parallel][installing_components_0] installing components task failed: Detected 6 failures: InvalidParameterValue: validation failed: [resource name must be unique; found duplicates: [00_1_count_table_failures, 00_2_count_total_databases, 00_3_count_total_tables, 00_4_count_total_views, 00_5_count_external_locations, 00_6_count_total_udfs, 00_7_count_storage_credentials, 01_0_compatibility, 01_1_count_jobs, 01_2_count_table_by_storage, 01_3_count_table_by_type_location_format, 05_0_object_readiness, 05_2_assessment_summary, 10_0_database_summary, 10_1_all_tables, 10_2_all_udfs, 15_0_external_locations, 15_3_mount_points, 20_0_clusters, 20_1_cluster_policies, 30_3_job_details, 30_3_jobs, 30_4_submit_runs, 30_5_submit_runs, 40_0_grants, 40_1_pipelines, 40_2_global_init_scripts, 40_3_logs]], InvalidParameterValue: validation failed: [resource name must be unique; found duplicates: [00_4_is_incompatible_submit_run_detected, 01_2_group_migration, 01_5_group_migration_complexity, 02_2_uc_data_modeling, 02_5_uc_data_modeling_complexity, 03_2_data_migration_summary, 03_5_data_migration_complexity, 04_1_data_migration_effort]], InvalidParameterValue: validation failed: [resource name must be unique; found duplicates: [01_0_compute_access_mode_limitation_summary, 03_0_cluster_summary]], InvalidParameterValue: validation failed: [resource name must be unique; found duplicates: [01_1_data_object_migration_summary, 02_1_code_compatibility_problems, 02_1_data_reconciliation_summary, 03_1_data_reconciliation_status, 04_1_remaining_hms_tables]], InvalidParameterValue: validation failed: [resource name must be unique; found duplicates: [01_1_group_migration_failures]], InvalidParameterValue: validation failed: [resource name must be unique; found duplicates: [05_0_azure_service_principals]]: Traceback (most recent call last):
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/labs/blueprint/parallel.py", line 158, in inner
    return func(*args, **kwargs), None
  File "/Users/serge.smertin/.databricks/labs/ucx/lib/src/databricks/labs/ucx/install.py", line 518, in _create_database_and_dashboards
    Threads.strict("installing dashboards", list(self._get_create_dashboard_tasks()))
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/labs/blueprint/parallel.py", line 63, in strict
    raise ManyError(errs)
databricks.labs.blueprint.parallel.ManyError: Detected 6 failures: InvalidParameterValue: validation failed: [resource name must be unique; found duplicates: [00_1_count_table_failures, 00_2_count_total_databases, 00_3_count_total_tables, 00_4_count_total_views, 00_5_count_external_locations, 00_6_count_total_udfs, 00_7_count_storage_credentials, 01_0_compatibility, 01_1_count_jobs, 01_2_count_table_by_storage, 01_3_count_table_by_type_location_format, 05_0_object_readiness, 05_2_assessment_summary, 10_0_database_summary, 10_1_all_tables, 10_2_all_udfs, 15_0_external_locations, 15_3_mount_points, 20_0_clusters, 20_1_cluster_policies, 30_3_job_details, 30_3_jobs, 30_4_submit_runs, 30_5_submit_runs, 40_0_grants, 40_1_pipelines, 40_2_global_init_scripts, 40_3_logs]], InvalidParameterValue: validation failed: [resource name must be unique; found duplicates: [00_4_is_incompatible_submit_run_detected, 01_2_group_migration, 01_5_group_migration_complexity, 02_2_uc_data_modeling, 02_5_uc_data_modeling_complexity, 03_2_data_migration_summary, 03_5_data_migration_complexity, 04_1_data_migration_effort]], InvalidParameterValue: validation failed: [resource name must be unique; found duplicates: [01_0_compute_access_mode_limitation_summary, 03_0_cluster_summary]], InvalidParameterValue: validation failed: [resource name must be unique; found duplicates: [01_1_data_object_migration_summary, 02_1_code_compatibility_problems, 02_1_data_reconciliation_summary, 03_1_data_reconciliation_status, 04_1_remaining_hms_tables]], InvalidParameterValue: validation failed: [resource name must be unique; found duplicates: [01_1_group_migration_failures]], InvalidParameterValue: validation failed: [resource name must be unique; found duplicates: [05_0_azure_service_principals]]
10:46:40 ERROR [d.l.blueprint.parallel] More than half 'installing components' tasks failed: 0% results available (0/2). Took 0:00:23.242086
Traceback (most recent call last):
  File "/Users/serge.smertin/.databricks/labs/ucx/lib/src/databricks/labs/ucx/install.py", line 899, in <module>
    workspace_installer.run()
  File "/Users/serge.smertin/.databricks/labs/ucx/lib/src/databricks/labs/ucx/install.py", line 211, in run
    raise err
  File "/Users/serge.smertin/.databricks/labs/ucx/lib/src/databricks/labs/ucx/install.py", line 207, in run
    workspace_installation.run()
  File "/Users/serge.smertin/.databricks/labs/ucx/lib/src/databricks/labs/ucx/install.py", line 505, in run
    Threads.strict("installing components", install_tasks)
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/labs/blueprint/parallel.py", line 62, in strict
    raise errs[0]
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/labs/blueprint/parallel.py", line 158, in inner
    return func(*args, **kwargs), None
  File "/Users/serge.smertin/.databricks/labs/ucx/lib/src/databricks/labs/ucx/install.py", line 518, in _create_database_and_dashboards
    Threads.strict("installing dashboards", list(self._get_create_dashboard_tasks()))
  File "/Users/serge.smertin/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/labs/blueprint/parallel.py", line 63, in strict
    raise ManyError(errs)
databricks.labs.blueprint.parallel.ManyError: Detected 6 failures: InvalidParameterValue: validation failed: [resource name must be unique; found duplicates: [00_1_count_table_failures, 00_2_count_total_databases, 00_3_count_total_tables, 00_4_count_total_views, 00_5_count_external_locations, 00_6_count_total_udfs, 00_7_count_storage_credentials, 01_0_compatibility, 01_1_count_jobs, 01_2_count_table_by_storage, 01_3_count_table_by_type_location_format, 05_0_object_readiness, 05_2_assessment_summary, 10_0_database_summary, 10_1_all_tables, 10_2_all_udfs, 15_0_external_locations, 15_3_mount_points, 20_0_clusters, 20_1_cluster_policies, 30_3_job_details, 30_3_jobs, 30_4_submit_runs, 30_5_submit_runs, 40_0_grants, 40_1_pipelines, 40_2_global_init_scripts, 40_3_logs]], InvalidParameterValue: validation failed: [resource name must be unique; found duplicates: [00_4_is_incompatible_submit_run_detected, 01_2_group_migration, 01_5_group_migration_complexity, 02_2_uc_data_modeling, 02_5_uc_data_modeling_complexity, 03_2_data_migration_summary, 03_5_data_migration_complexity, 04_1_data_migration_effort]], InvalidParameterValue: validation failed: [resource name must be unique; found duplicates: [01_0_compute_access_mode_limitation_summary, 03_0_cluster_summary]], InvalidParameterValue: validation failed: [resource name must be unique; found duplicates: [01_1_data_object_migration_summary, 02_1_code_compatibility_problems, 02_1_data_reconciliation_summary, 03_1_data_reconciliation_status, 04_1_remaining_hms_tables]], InvalidParameterValue: validation failed: [resource name must be unique; found duplicates: [01_1_group_migration_failures]], InvalidParameterValue: validation failed: [resource name must be unique; found duplicates: [05_0_azure_service_principals]]
```
```

**Comment by JCZuurmond** [comment]
Upgrading the Databricks cli resolves the issue
