### ISSUE TITLE
[BUG]: OSError: [Errno 95] Operation not supported: `/Workspace/Users/.../path/to/notebook`

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#2888]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

apparently, `pathlib.Path` is used in place of `WorkspacePath` and we try to read notebook as a file, but WSFS doesn't support it.

```
13:03:42 ERROR [d.l.blueprint.parallel][linting_workflows_5] linting workflows(657323031729870) task failed: [Errno 95] Operation not supported: '/Workspace/Users/........./jobs/notebooks/landing/fetch_data': Traceback (most recent call last):
  File ".../site-packages/databricks/labs/blueprint/parallel.py", line 158, in inner
    return func(*args, **kwargs), None
           ^^^^^^^^^^^^^^^^^^^^^
  File ".../site-packages/databricks/labs/ucx/source_code/jobs.py", line 399, in lint_job
    problems, dfsas, tables = self._lint_job(job)
                              ^^^^^^^^^^^^^^^^^^^
  File ".../site-packages/databricks/labs/ucx/source_code/jobs.py", line 418, in _lint_job
    graph, advices, session_state = self._build_task_dependency_graph(task, job)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../site-packages/databricks/labs/ucx/source_code/jobs.py", line 467, in _build_task_dependency_graph
    problems = container.build_dependency_graph(graph)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../site-packages/databricks/labs/ucx/source_code/jobs.py", line 133, in build_dependency_graph
    return list(self._register_task_dependencies(parent))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../site-packages/databricks/labs/ucx/source_code/jobs.py", line 139, in _register_task_dependencies
    yield from self._register_notebook(graph)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../site-packages/databricks/labs/ucx/source_code/jobs.py", line 221, in _register_notebook
    return graph.register_notebook(path, False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../site-packages/databricks/labs/ucx/source_code/graph.py", line 58, in register_notebook
    maybe_graph = self.register_dependency(maybe.dependency)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../site-packages/databricks/labs/ucx/source_code/graph.py", line 89, in register_dependency
    container = dependency.load(self.path_lookup)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../site-packages/databricks/labs/ucx/source_code/graph.py", line 327, in load
    return self._loader.load_dependency(path_lookup, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../site-packages/databricks/labs/ucx/source_code/notebooks/loaders.py", line 60, in load_dependency
    content = absolute_path.read_text("utf-8")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 1059, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 1045, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 95] Operation not supported: '/Workspace/Users/........./jobs/notebooks/landing/fetch_data'
```

**Comment by asnare** [comment]
Is there a backtrace, logs, or some reference for this?

**Comment by nfx** [comment]
@asnare if a file has no extension and starts with `/Workspace`, then it needs to be converted into a `WorkspacePath` (stripping the `/Workspace` prefix).

we also have another issue there - paths like `/foo/bar/baz/../../x` that have to convert to `/foo/x`, because workspace API doesn't understand relative paths.

**Comment by asnare** [comment]
[Here](https://github.com/databrickslabs/ucx/blob/bb3768a6c94ba9a8c3eea4fb770c2dcd1511121b/src/databricks/labs/ucx/source_code/notebooks/loaders.py#L90) is another place where it could be going wrong.

**Comment by nfx** [comment]
@asnare got you the stack trace
