### ISSUE TITLE
[BUG]: guess_external_locations fail with AssertionError

### ISSUE THREAD

**Issue by antoniopinheirofilho** [databrickslabs/ucx#3091]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

guess_external_locations fails when running the assessment job for a customer

### Expected Behavior

It should handle the exception

### Cloud

Azure

### Operating System

macOS

### Version

latest via Databricks CLI

### Relevant log output

```shell
20:59:26 DEBUG [databricks] {MainThread} Task crash details
Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/databricks/labs/ucx/runtime.py", line 102, in trigger
    current_task(ctx)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/databricks/labs/ucx/assessment/workflows.py", line 73, in guess_external_locations
    ctx.external_locations.snapshot()
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/databricks/labs/ucx/framework/crawlers.py", line 108, in snapshot
    return self._snapshot(self._try_fetch, self._crawl, force_refresh=force_refresh)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/databricks/labs/ucx/framework/crawlers.py", line 158, in _snapshot
    loaded_records = list(loader())
                          ^^^^^^^^
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/databricks/labs/ucx/hive_metastore/locations.py", line 246, in _crawl
    return self._external_locations()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/databricks/labs/ucx/hive_metastore/locations.py", line 184, in _external_locations
    assert curr.location is not None
AssertionError
```

**Comment by FastLee** [comment]
Can you look at your table location and find out if you have a table that is located on the root storage of another table?
For example:
table a location: s3://location/tables/table_a
table b location: s3://location

**Comment by FastLee** [comment]
Found the issue. Tables on root location weren't handled properly. Can you confirm this is the case.

**Comment by antoniopinheirofilho** [comment]
Hard to be 100% sure, but it appears to be the case.
