### ISSUE TITLE
Upgrade Fails with "Asset is already in trash"

### ISSUE THREAD

**Issue by pohlposition** [databrickslabs/ucx#347]
I installed the 0.1.1 release
- everything installed correctly

I later downloaded the 0.2.0 release and ran install.sh again

The install failed with the following stacktrace

`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/jason/git/ucx_releases/ucx-0.2.0/src/databricks/labs/ucx/install.py", line 547, in <module>
    installer.run()
  File "/Users/jason/git/ucx_releases/ucx-0.2.0/src/databricks/labs/ucx/install.py", line 77, in run
    self._run_configured()
  File "/Users/jason/git/ucx_releases/ucx-0.2.0/src/databricks/labs/ucx/install.py", line 80, in _run_configured
    self._create_dashboards()
  File "/Users/jason/git/ucx_releases/ucx-0.2.0/src/databricks/labs/ucx/install.py", line 106, in _create_dashboards
    self._dashboards["assessment"] = dash.create_dashboard()
                                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jason/git/ucx_releases/ucx-0.2.0/src/databricks/labs/ucx/framework/dashboards.py", line 110, in create_dashboard
    self._store_query_state(desired_queries)
  File "/Users/jason/git/ucx_releases/ucx-0.2.0/src/databricks/labs/ucx/framework/dashboards.py", line 189, in _store_query_state
    destructors[name](v)
  File "/private/var/folders/9l/118q49zs0kx7vs5qnwf9flc40000gp/T/tmp.ymyAK1W9/lib/python3.11/site-packages/databricks/sdk/service/sql.py", line 3021, in delete
    self._api.do('DELETE', f'/api/2.0/preview/sql/queries/{query_id}', headers=headers)
  File "/private/var/folders/9l/118q49zs0kx7vs5qnwf9flc40000gp/T/tmp.ymyAK1W9/lib/python3.11/site-packages/databricks/sdk/core.py", line 1084, in do
    raise self._make_nicer_error(status_code=response.status_code, **payload) from None
databricks.sdk.core.DatabricksError: Asset is already in trash
`

**Comment by pohlposition** [comment]
That didn't format well.  Raw text...

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/jason/git/ucx_releases/ucx-0.2.0/src/databricks/labs/ucx/install.py", line 547, in <module>
    installer.run()
  File "/Users/jason/git/ucx_releases/ucx-0.2.0/src/databricks/labs/ucx/install.py", line 77, in run
    self._run_configured()
  File "/Users/jason/git/ucx_releases/ucx-0.2.0/src/databricks/labs/ucx/install.py", line 80, in _run_configured
    self._create_dashboards()
  File "/Users/jason/git/ucx_releases/ucx-0.2.0/src/databricks/labs/ucx/install.py", line 106, in _create_dashboards
    self._dashboards["assessment"] = dash.create_dashboard()
                                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jason/git/ucx_releases/ucx-0.2.0/src/databricks/labs/ucx/framework/dashboards.py", line 110, in create_dashboard
    self._store_query_state(desired_queries)
  File "/Users/jason/git/ucx_releases/ucx-0.2.0/src/databricks/labs/ucx/framework/dashboards.py", line 189, in _store_query_state
    destructors[name](v)
  File "/private/var/folders/9l/118q49zs0kx7vs5qnwf9flc40000gp/T/tmp.ymyAK1W9/lib/python3.11/site-packages/databricks/sdk/service/sql.py", line 3021, in delete
    self._api.do('DELETE', f'/api/2.0/preview/sql/queries/{query_id}', headers=headers)
  File "/private/var/folders/9l/118q49zs0kx7vs5qnwf9flc40000gp/T/tmp.ymyAK1W9/lib/python3.11/site-packages/databricks/sdk/core.py", line 1084, in do
    raise self._make_nicer_error(status_code=response.status_code, **payload) from None
databricks.sdk.core.DatabricksError: Asset is already in trash

**Comment by FastLee** [comment]
I did some analysis @nfx why are we deleting the queries in state.json and not just getting rid of the whole folder?
