### ISSUE TITLE
Installation failing for GCP workspace

### ISSUE THREAD

**Issue by dipankarkush-db** [databrickslabs/ucx#419]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/bbandi_petsmart_com/ucx/ucx/src/databricks/labs/ucx/install.py", line 713, in <module>
    installer.run()
  File "/home/bbandi_petsmart_com/ucx/ucx/src/databricks/labs/ucx/install.py", line 112, in run
    self._run_configured()
  File "/home/bbandi_petsmart_com/ucx/ucx/src/databricks/labs/ucx/install.py", line 116, in _run_configured
    self._create_jobs()
  File "/home/bbandi_petsmart_com/ucx/ucx/src/databricks/labs/ucx/install.py", line 340, in _create_jobs
    self._deployed_steps[step_name] = self._ws.jobs.create(**settings).job_id
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmp.UaQueFGpkl/lib/python3.11/site-packages/databricks/sdk/service/jobs.py", line 2999, in create
    res = self._api.do('POST', '/api/2.1/jobs/create', body=body, headers=headers)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmp.UaQueFGpkl/lib/python3.11/site-packages/databricks/sdk/core.py", line 1061, in do
    return retryable(self._perform)(method,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmp.UaQueFGpkl/lib/python3.11/site-packages/databricks/sdk/retries.py", line 47, in wrapper
    raise err
  File "/tmp/tmp.UaQueFGpkl/lib/python3.11/site-packages/databricks/sdk/retries.py", line 29, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmp.UaQueFGpkl/lib/python3.11/site-packages/databricks/sdk/core.py", line 1150, in _perform
    raise self._make_nicer_error(response=response, **payload) from None
databricks.sdk.core.DatabricksError:
The provided tag value (v0.3.1+2320231009205751) contains invalid character. The value must match the regular
expression ^(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?$.

**Comment by dipankarkush-db** [comment]
I tried in fe-prod and it failed with the same error. It works fine with AWS and Azure -

01:58  INFO [_] Creating configuration file: /Users/dipankar.kushari@databricks.com/.ucx/config.yml
Open config file in the browser and continue installing? (default: yes):
01:59  INFO [_] Uploading wheel to dbfs:/Users/dipankar.kushari@databricks.com/.ucx/wheels/databricks_labs_ucx-0.3.1+2720231010015907-py3-none-any.whl
01:59  INFO [_] Uploading wheel to /Workspace/Users/dipankar.kushari@databricks.com/.ucx/wheels/databricks_labs_ucx-0.3.1+2720231010015907-py3-none-any.whl
01:59  INFO [_] Creating new job configuration for step=assessment
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/dipankar.kushari/Library/CloudStorage/GoogleDrive-dipankar.kushari@databricks.com/My Drive/10x/UC/UCX/ucx/src/databricks/labs/ucx/install.py", line 644, in <module>
    installer.run()
  File "/Users/dipankar.kushari/Library/CloudStorage/GoogleDrive-dipankar.kushari@databricks.com/My Drive/10x/UC/UCX/ucx/src/databricks/labs/ucx/install.py", line 82, in run
    self._run_configured()
  File "/Users/dipankar.kushari/Library/CloudStorage/GoogleDrive-dipankar.kushari@databricks.com/My Drive/10x/UC/UCX/ucx/src/databricks/labs/ucx/install.py", line 86, in _run_configured
    self._create_jobs()
  File "/Users/dipankar.kushari/Library/CloudStorage/GoogleDrive-dipankar.kushari@databricks.com/My Drive/10x/UC/UCX/ucx/src/databricks/labs/ucx/install.py", line 284, in _create_jobs
    self._deployed_steps[step_name] = self._ws.jobs.create(**settings).job_id
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/76/zv4jmwyd2djf6c35f2nly9br0000gp/T/tmp.6lb6NBtPaF/lib/python3.11/site-packages/databricks/sdk/service/jobs.py", line 2999, in create
    res = self._api.do('POST', '/api/2.1/jobs/create', body=body, headers=headers)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/76/zv4jmwyd2djf6c35f2nly9br0000gp/T/tmp.6lb6NBtPaF/lib/python3.11/site-packages/databricks/sdk/core.py", line 1061, in do
    return retryable(self._perform)(method,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/76/zv4jmwyd2djf6c35f2nly9br0000gp/T/tmp.6lb6NBtPaF/lib/python3.11/site-packages/databricks/sdk/retries.py", line 47, in wrapper
    raise err
  File "/private/var/folders/76/zv4jmwyd2djf6c35f2nly9br0000gp/T/tmp.6lb6NBtPaF/lib/python3.11/site-packages/databricks/sdk/retries.py", line 29, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/76/zv4jmwyd2djf6c35f2nly9br0000gp/T/tmp.6lb6NBtPaF/lib/python3.11/site-packages/databricks/sdk/core.py", line 1150, in _perform
    raise self._make_nicer_error(response=response, **payload) from None
databricks.sdk.core.DatabricksError:
The provided tag value (v0.3.1+2720231010015915) contains invalid character. The value must match the regular
expression ^(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?$.

**Comment by dipankarkush-db** [comment]
Related issue - https://github.com/databricks/databricks-sdk-py/issues/394

**Comment by alexott** [comment]
GCP doesn't allow characters like `@` in tags - it looks like we're using the user's email as a tag...

**Comment by larsgeorge-db** [comment]
Yeah, seems to be the tagging of the workflows... sigh...

![image](https://github.com/databrickslabs/ucx/assets/136075433/26edcb85-db55-4927-9cea-6863852d3173)

**Comment by dipankarkush-db** [comment]
The provided tag value (v0.3.1+2720231010022853) contains invalid character. The value must match the regular
expression ^(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?$. Its the version number.

**Comment by larsgeorge-db** [comment]
That part is clear it seems, but why?

![image](https://github.com/databrickslabs/ucx/assets/136075433/46c7a211-6952-4951-9ff5-f38e349dc5d6)

It seems the expression can capture this?

**Comment by larsgeorge-db** [comment]
Ah no, sorry, this is Java/Scala in the end, so the issue is the added timestamp

![image](https://github.com/databrickslabs/ucx/assets/136075433/a41e3474-4a2f-48d1-88e0-7fb36a6a223d)

![image](https://github.com/databrickslabs/ucx/assets/136075433/fcf5982b-450d-423b-8e90-47d529a06303)

**Comment by larsgeorge-db** [comment]
This only happens when you have a `.git` folder present (as in, you are a developer). For releases from our GitHub pages downloaded as tarballs, this is not happening (no hash is attached) and the install should work:

See https://github.com/databrickslabs/ucx/blob/main/src/databricks/labs/ucx/install.py#L610

**Comment by larsgeorge-db** [comment]
We could add a `... and self._ws.config.is_gcp:` to get around this.
