### ISSUE TITLE
Azure Service Principal - Cluster Policy Not Found

### ISSUE THREAD

**Issue by dipankarkush-db** [databrickslabs/ucx#502]
The Assessment task for AzureServicePrincipalCrawler failed with the below error -

Stack Trace from the run

```
< {
<   "created_at_timestamp": 1646931054000,
<   "definition": "{\"autoscale.max_workers\":{\"defaultValue\":8,\"isOptional\":true,\"maxValue\":64,\"type\":\"range\"},\"auto... (1856 more bytes)",
<   "is_default": false,
<   "name": "TmTds - Job Clusters",
<   "policy_id": "C96203490C000437"
< }
20:07:19 DEBUG [databricks.sdk] {MainThread} GET /api/2.0/policies/clusters/get?policy_id=C96203490C0004AD
< 404 Not Found
< {
<   "error_code": "RESOURCE_DOES_NOT_EXIST",
<   "message": "Can't find a cluster policy with id: XYZABCDE."
< }
20:07:19 ERROR [databricks.labs.ucx] {MainThread} Task crashed. Execute `databricks workspace export /Users/s111@aaa.com/.ucx/logs/assessment/run-4573409/assess_azure_service_principals.log` locally to troubleshoot with more details. Can't find a cluster policy with id: XYZABCDE.
20:07:19 DEBUG [databricks] {MainThread} Task crash details
Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/tasks.py", line 149, in trigger
    current_task.fn(cfg)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/runtime.py", line 266, in assess_azure_service_principals
    crawler.snapshot()
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/assessment/crawlers.py", line 369, in snapshot
    return self._snapshot(self._try_fetch, self._crawl)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/crawlers.py", line 229, in _snapshot
    loaded_records = list(loader())
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/assessment/crawlers.py", line 182, in _crawl
    all_relevant_service_principals = self._get_relevant_service_principals()
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/assessment/crawlers.py", line 277, in _get_relevant_service_principals
    temp_list = self._list_all_jobs_with_spn_in_spark_conf()
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/assessment/crawlers.py", line 297, in _list_all_jobs_with_spn_in_spark_conf
    policy = self._ws.cluster_policies.get(cluster_config.policy_id)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/service/compute.py", line 3573, in get
    res = self._api.do('GET', '/api/2.0/policies/clusters/get', query=query, headers=headers)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/core.py", line 1061, in do
    return retryable(self._perform)(method,
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/retries.py", line 47, in wrapper
    raise err
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/retries.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/core.py", line 1151, in _perform
    raise self._make_nicer_error(response=response, **payload) from None
databricks.sdk.core.DatabricksError: Can't find a cluster policy with id: XYZABCDE.

```

**Comment by mwojtyczka** [comment]
Should already be fixed by [PR 486](https://github.com/databrickslabs/ucx/pull/486)
