### ISSUE TITLE
Assessment task failed in pipeline crawler

### ISSUE THREAD

**Issue by dipankarkush-db** [databrickslabs/ucx#504]
The assessment task failed in pipeline crawler

Stack trace below -

`20:06:56 DEBUG [databricks.labs.ucx.framework.crawlers] {MainThread} [hive_metastore.ucx_sd.pipelines] found 62 new records for pipelines
20:06:56 ERROR [databricks.labs.ucx] {MainThread} Task crashed. Execute `databricks workspace export /Users/s210@ccc.com/.ucx/logs/assessment/run-457/assess_pipelines.log` locally to troubleshoot with more details. [CANNOT_BE_NONE] Argument `obj` can not be None.
20:06:56 DEBUG [databricks] {MainThread} Task crash details
Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/tasks.py", line 149, in trigger
    current_task.fn(cfg)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/runtime.py", line 250, in assess_pipelines
    crawler.snapshot()
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/assessment/crawlers.py", line 400, in snapshot
    return self._snapshot(self._try_fetch, self._crawl)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/crawlers.py", line 230, in _snapshot
    self._append_records(loaded_records)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/crawlers.py", line 235, in _append_records
    self._backend.save_table(self._full_name, items, self._klass, mode="append")
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/crawlers.py", line 135, in save_table
    df = self._spark.createDataFrame(rows, self._schema_for(rows[0]))
  File "/databricks/spark/python/pyspark/instrumentation_utils.py", line 47, in wrapper
    res = func(*args, **kwargs)
  File "/databricks/spark/python/pyspark/sql/session.py", line 1507, in createDataFrame
    return self._create_dataframe(
  File "/databricks/spark/python/pyspark/sql/session.py", line 1557, in _create_dataframe
    rdd, struct = self._createFromLocal(map(prepare, data), schema)
  File "/databricks/spark/python/pyspark/sql/session.py", line 1135, in _createFromLocal
    internal_data, struct = self._wrap_data_schema(data, schema)
  File "/databricks/spark/python/pyspark/sql/session.py", line 1099, in _wrap_data_schema
    data = list(data)
  File "/databricks/spark/python/pyspark/sql/session.py", line 1523, in prepare
    verify_func(obj)
  File "/databricks/spark/python/pyspark/sql/types.py", line 2206, in verify
    verify_value(obj)
  File "/databricks/spark/python/pyspark/sql/types.py", line 2183, in verify_struct
    verifier(d.get(f))
  File "/databricks/spark/python/pyspark/sql/types.py", line 2205, in verify
    if not verify_nullability(obj):
  File "/databricks/spark/python/pyspark/sql/types.py", line 2008, in verify_nullability
    raise PySparkValueError(
pyspark.errors.exceptions.base.PySparkValueError: [CANNOT_BE_NONE] Argument `obj` can not be None.
`

**Comment by william-conti** [comment]
Should be fixed by https://github.com/databrickslabs/ucx/pull/485
