### ISSUE TITLE
Install.sh is failing

### ISSUE THREAD

**Issue by karthikgk25** [databrickslabs/ucx#528]
Running the install.sh is failing after creating dashboard step. Using gitbash from windows machine. Please advice.

Open config file in the browser (default: yes):
11:56  INFO [__main__] Creating dashboards...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\abc\Desktop\NGCX\Vsc Code\UCX\ucx\src\databricks\labs\ucx\install.py", line 786, in <module>
    installer.run()
  File "C:\Users\abc\Desktop\NGCX\Vsc Code\UCX\ucx\src\databricks\labs\ucx\install.py", line 104, in run
    self._run_configured()
  File "C:\Users\abc\Desktop\NGCX\Vsc Code\UCX\ucx\src\databricks\labs\ucx\install.py", line 108, in _run_configured
    self._create_jobs()
  File "C:\Users\abc\Desktop\NGCX\Vsc Code\UCX\ucx\src\databricks\labs\ucx\install.py", line 343, in _create_jobs
    remote_wheel = self._upload_wheel()
                   ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abc\Desktop\NGCX\Vsc Code\UCX\ucx\src\databricks\labs\ucx\install.py", line 485, in _upload_wheel
    local_wheel = self._build_wheel(tmp_dir)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abc\Desktop\NGCX\Vsc Code\UCX\ucx\src\databricks\labs\ucx\install.py", line 697, in _build_wheel
    subprocess.run(
  File "C:\Program Files\Python312\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Users\\abc\\AppData\\Local\\Temp\\tmp.FgK3HhZMlV\\Scripts\\python.exe', '-m', 'pip', 'wheel', '--no-deps', '--wheel-dir', 'C:\\Users\\gurramk\\AppData\\Local\\Temp\\tmpucrzmd68', WindowsPath('C:/Users/abc/AppData/Local/Temp/tmpucrzmd68/working-copy')]' returned non-zero exit status 1.

**Comment by larsgeorge-db** [comment]
What version/branch/latest-commit did you use to ru this? Will try the same if you provide the details.

Could you confirm it is not something with Python? What version are you using?

**Comment by karthikgk25** [comment]
Thanks for the response. it's an access issue.  Closing the bug.
