### ISSUE TITLE
[Bug] Issue parsing custom spark version 

### ISSUE THREAD

**Issue by irinaplacinta-db** [databrickslabs/ucx#537]
The `assess_clusters` task is failing as it cannot extract the spark version for a Serverless cluster with custom spark version `custom:snapshot__14.x-snapshot-scala2.12__databricks-universe__14.1.0__52ca36e__6dda39a__jenkins__6a6b9d2__format-3`.

Error:
```
Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/tasks.py", line 149, in trigger
    current_task.fn(cfg)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/runtime.py", line 234, in assess_clusters
    crawler.snapshot()
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/assessment/crawlers.py", line 524, in snapshot
    return self._snapshot(self._try_fetch, self._crawl)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/crawlers.py", line 240, in _snapshot
    loaded_records = list(loader())
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/assessment/crawlers.py", line 448, in _crawl
    return list(self._assess_clusters(all_clusters))
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/assessment/crawlers.py", line 466, in _assess_clusters
    support_status = spark_version_compatibility(cluster.spark_version)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/assessment/crawlers.py", line 134, in spark_version_compatibility
    version = int(first_components[0]), int(first_components[1])
ValueError: invalid literal for int() with base 10: 'custom:snapshot__14'
```

Code is trying to extract an integer value from the first part of the spark version, expecting something like `13.3.x`, but in this case we have `custom:snapshot__14.x....`.

https://github.com/databrickslabs/ucx/blob/f9b6117711eaf57e353068583b09aea79f932605/src/databricks/labs/ucx/assessment/crawlers.py#L134C5-L134C5

**Comment by nfx** [comment]
Thank you for the feature request! Currently, the team operates in a limited capacity, carefully prioritizing, and we cannot provide a timeline to implement this feature. Please make a Pull Request if you'd like to see this feature sooner, and we'll guide you through the journey.

**Comment by nfx** [comment]
this issue is only releated to databricks staging environments
