### ISSUE TITLE
ValueError: default auth: cannot configure default credentials

### ISSUE THREAD

**Issue by Ritsch1** [databrickslabs/ucx#547]
Hi,

While running the install.sh script, I am encountering the following error:
![image](https://github.com/databrickslabs/ucx/assets/49514733/760ee59d-80d7-459a-b8ed-5eab8b2c4b3a)

Checking the source code, its pointing to the DefaultCredentials class which whose __call__ function is raising a ValueError.
[databricks-sdk-py/databricks/sdk/core.py at main · databricks/databricks-sdk-py · GitHub](https://github.com/databricks/databricks-sdk-py/blob/main/databricks/sdk/core.py#L501)

I followed the instructions (setting up databricks cli which works & having the correct Python Version)

Does anyone have an idea why the script is failing?

**Comment by pohlposition** [comment]
The new labs command group in CLI will fix this.

**Comment by nfx** [comment]
@Ritsch1 please install app via `databricks labs install ucx`

**Comment by tauhlim** [comment]
Hi team, I just tested using the new `labs` command group in CLI but still facing similar issues. I have verified that CLI authentication is working fine (can run other commands like `databricks clusters list`) but having issues with UCX installation.

Full stacktrace below

```
~ % databricks labs install ucx --log-level TRACE
13:46:03  INFO start pid=32671 version=0.219.0 args="databricks, labs, install, ucx, --log-level, TRACE"
13:46:03 DEBUG Latest ucx version is: v0.22.0 pid=32671
13:46:03 DEBUG Reading labs.yml@v0.22.0 from databrickslabs/ucx pid=32671
13:46:03 TRACE GET https://raw.githubusercontent.com/databrickslabs/ucx/v0.22.0/labs.yml pid=32671
13:46:04 DEBUG Loading login configuration from: /Users/my.username/.databricks/labs/ucx/config/login.json pid=32671
13:46:04 DEBUG Using workspace-level login profile: e2-demo-field-eng pid=32671
13:46:04 TRACE Loading config via cli-env pid=32671 sdk=true
13:46:04 TRACE Loading config via environment pid=32671 sdk=true
13:46:04 TRACE Loading config via config-file pid=32671 sdk=true
13:46:04 DEBUG Loading e2-demo-field-eng profile from /Users/my.username/.databrickscfg pid=32671 sdk=true
13:46:04 DEBUG Resolved login: Config: host=https://e2-demo-field-eng.cloud.databricks.com/, profile=e2-demo-field-eng, config_file=/Users/my.username/.databrickscfg pid=32671 sdk=true
13:46:04 DEBUG Writing auth configuration to: /Users/my.username/.databricks/labs/ucx/config/login.json pid=32671
⣾ Cleaning up previous installation if necessary13:46:04 DEBUG Downloading zipball for v0.22.0 from databrickslabs/ucx pid=32671
13:46:04 TRACE GET https://api.github.com/repos/databrickslabs/ucx/zipball/v0.22.0 pid=32671
⢿ Downloading and unpacking zipball for v0.22.013:46:06 DEBUG Unpacking zipball to: /Users/my.username/.databricks/labs/ucx/lib pid=32671
⣾ Detecting all installed Python interpreters on the system13:46:06 DEBUG found 7 potential alternative Python versions in $PATH pid=32671
13:46:06 DEBUG running: /opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/bin/python3.12 --version pid=32671
13:46:06 DEBUG /opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/bin/python3.12 --version: Python 3.12.2 pid=32671
13:46:06 DEBUG running: /opt/homebrew/Cellar/python@3.10/3.10.13_2/Frameworks/Python.framework/Versions/3.10/bin/python3.10 --version pid=32671
13:46:06 DEBUG /opt/homebrew/Cellar/python@3.10/3.10.13_2/Frameworks/Python.framework/Versions/3.10/bin/python3.10 --version: Python 3.10.13 pid=32671
13:46:06 DEBUG running: /opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/bin/python3.11 --version pid=32671
13:46:06 DEBUG /opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/bin/python3.11 --version: Python 3.11.8 pid=32671
13:46:06 DEBUG running: /opt/homebrew/Cellar/python@3.9/3.9.18_2/Frameworks/Python.framework/Versions/3.9/bin/python3.9 --version pid=32671
13:46:06 DEBUG /opt/homebrew/Cellar/python@3.9/3.9.18_2/Frameworks/Python.framework/Versions/3.9/bin/python3.9 --version: Python 3.9.18 pid=32671
13:46:06 DEBUG running: /usr/bin/python3 --version pid=32671
13:46:06 DEBUG /usr/bin/python3 --version: Python 3.9.6 pid=32671
13:46:06 DEBUG Detected Python v3.10.13 at: /opt/homebrew/Cellar/python@3.10/3.10.13_2/Frameworks/Python.framework/Versions/3.10/bin/python3.10 pid=32671
13:46:06 DEBUG Creating Python Virtual Environment at: /Users/my.username/.databricks/labs/ucx/state/venv pid=32671
13:46:06 DEBUG running: /opt/homebrew/Cellar/python@3.10/3.10.13_2/Frameworks/Python.framework/Versions/3.10/bin/python3.10 -m venv /Users/my.username/.databricks/labs/ucx/state/venv pid=32671
⣟ Creating Virtual Environment with Python v3.10.1313:46:07 DEBUG Installing Python dependencies for: /Users/my.username/.databricks/labs/ucx/lib pid=32671
13:46:07 DEBUG running: /Users/my.username/.databricks/labs/ucx/state/venv/bin/python3 -m pip install . pid=32671
13:46:09 DEBUG Writing installed version info to: /Users/my.username/.databricks/labs/ucx/state/version.json pid=32671
13:46:09 DEBUG Launching installer script src/databricks/labs/ucx/install.py in /Users/my.username/.databricks/labs/ucx/lib pid=32671
13:46:09 DEBUG Loading login configuration from: /Users/my.username/.databricks/labs/ucx/config/login.json pid=32671
13:46:09 DEBUG Using workspace-level login profile: e2-demo-field-eng pid=32671
13:46:09 TRACE Loading config via cli-env pid=32671 sdk=true
13:46:09 TRACE Loading config via environment pid=32671 sdk=true
13:46:09 TRACE Loading config via config-file pid=32671 sdk=true
13:46:09 DEBUG Loading e2-demo-field-eng profile from /Users/my.username/.databrickscfg pid=32671 sdk=true
13:46:09 DEBUG Resolved login: Config: host=https://e2-demo-field-eng.cloud.databricks.com/, profile=e2-demo-field-eng, config_file=/Users/my.username/.databrickscfg pid=32671 sdk=true
13:46:09 DEBUG Passing down environment variables: DATABRICKS_HOST, DATABRICKS_AUTH_TYPE pid=32671
13:46:09 DEBUG starting: /Users/my.username/.databricks/labs/ucx/state/venv/bin/python3 src/databricks/labs/ucx/install.py pid=32671
13:46:09  INFO [d.l.ucx.install] Installing UCX v0.22.0
13:46:11  INFO [d.l.ucx.install] Please answer a couple of questions to configure Unity Catalog migration
Inventory Database stored in hive_metastore (default: ucx): tau_ucx
Log level (default: INFO): 
Number of threads (default: 8): 
Backup prefix (default: db-temp-): 
Choose how to map the workspace groups:
[0] Match by Name
[1] Apply a Prefix
[2] Apply a Suffix
[3] Match by External ID
[4] Regex Substitution
[5] Regex Matching
Enter a number between 0 and 5: 0
Comma-separated list of workspace group names to migrate. If not specified, we'll use all account-level groups with matching names to workspace-level groups (default: <ALL>): 
Do you use Terraform to deploy your infrastructure? (default: no): 
Comma-separated list of databases to migrate. If not specified, we'll use all databases in hive_metastore (default: <ALL>): 
Do you want to trigger assessment job after installation? (default: no): 

13:46:17  INFO [d.l.ucx.install] Fetching installations...
Traceback (most recent call last):
  File "/Users/my.username/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/config.py", line 442, in init_auth
    self._header_factory = self._credentials_provider(self)
  File "/Users/my.username/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/credentials_provider.py", line 626, in __call__
    raise ValueError(
ValueError: cannot configure default credentials, please check https://docs.databricks.com/en/dev-tools/auth.html#databricks-client-unified-authentication to configure credentials for your preferred authentication method.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/my.username/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/config.py", line 104, in __init__
    self.init_auth()
  File "/Users/my.username/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/config.py", line 447, in init_auth
    raise ValueError(f'{self._credentials_provider.auth_type()} auth: {e}') from e
ValueError: default auth: cannot configure default credentials, please check https://docs.databricks.com/en/dev-tools/auth.html#databricks-client-unified-authentication to configure credentials for your preferred authentication method.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/my.username/.databricks/labs/ucx/lib/src/databricks/labs/ucx/install.py", line 686, in <module>
    workspace_installer.run()
  File "/Users/my.username/.databricks/labs/ucx/lib/src/databricks/labs/ucx/install.py", line 164, in run
    config = self.configure(default_config)
  File "/Users/my.username/.databricks/labs/ucx/lib/src/databricks/labs/ucx/install.py", line 270, in configure
    return self._configure_new_installation(default_config)
  File "/Users/my.username/.databricks/labs/ucx/lib/src/databricks/labs/ucx/install.py", line 295, in _configure_new_installation
    self._check_inventory_database_exists(default_config.inventory_database)
  File "/Users/my.username/.databricks/labs/ucx/lib/src/databricks/labs/ucx/install.py", line 384, in _check_inventory_database_exists
    config = installation.load(WorkspaceConfig)
  File "/Users/my.username/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/labs/blueprint/installation.py", line 210, in load
    return self._unmarshal_type(as_dict, filename, type_ref)
  File "/Users/my.username/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/labs/blueprint/installation.py", line 378, in _unmarshal_type
    return cls._unmarshal(as_dict, [], type_ref)
  File "/Users/my.username/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/labs/blueprint/installation.py", line 622, in _unmarshal
    return cls._unmarshal_dataclass(inst, path, type_ref)
  File "/Users/my.username/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/labs/blueprint/installation.py", line 658, in _unmarshal_dataclass
    value = cls._unmarshal(raw, [*path, field_name], hint)
  File "/Users/my.username/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/labs/blueprint/installation.py", line 624, in _unmarshal
    return cls._unmarshal_union(inst, path, type_ref)
  File "/Users/my.username/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/labs/blueprint/installation.py", line 677, in _unmarshal_union
    value = cls._unmarshal(inst, path, variant)
  File "/Users/my.username/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/labs/blueprint/installation.py", line 636, in _unmarshal
    return databricks.sdk.core.Config(**inst)  # type: ignore[return-value]
  File "/Users/my.username/.databricks/labs/ucx/state/venv/lib/python3.10/site-packages/databricks/sdk/config.py", line 109, in __init__
    raise ValueError(message) from e
ValueError: default auth: cannot configure default credentials, please check https://docs.databricks.com/en/dev-tools/auth.html#databricks-client-unified-authentication to configure credentials for your preferred authentication method. Config: host=https://e2-demo-field-eng.cloud.databricks.com, auth_type=runtime. Env: DATABRICKS_HOST, DATABRICKS_AUTH_TYPE
Error: installer: exit status 1
```
