### ISSUE TITLE
API server downtime not handled

### ISSUE THREAD

**Issue by fannijako** [databrickslabs/ucx#556]
After an 504 Gateway Timeout, the apply permissions to backup groups job fails. There is no retry added on the workflow, nor is this error handled in the tool.

At a bigger workspace, restarting the job and building up the state again takes ~1 hour with every restart.

**Comment by nfx** [comment]
@fannijako Please share the relevant logs

**Comment by fannijako** [comment]
```
13:31:04 DEBUG [databricks.sdk] {MainThread} POST /api/2.0/preview/scim/v2/Groups
> {
>   "displayName": "db-temp-idm2bcd_dssi03prod_hdev6_read",
>   "members": [
>     {
>       "display": "**REDACTED**",
>       "value": "**REDACTED**"
>     },
>     "... (1959 additional elements)"
>   ],
>   "meta": {
>     "resourceType": "WorkspaceGroup"
>   }
> }
< 504 Gateway Timeout
< {
<   "error_code": "TEMPORARILY_UNAVAILABLE",
<   "message": "The service at /api/2.0/preview/scim/v2/Groups is taking too long to process your request. Pleas... (111 more bytes)"
< }
13:31:06 DEBUG [databricks.sdk] {MainThread} Retrying: matched Please try again later or try a faster operation. (sleeping ~1s)
13:31:07 ERROR [databricks.labs.ucx] {MainThread} Task crashed. Execute `databricks workspace export /Users/jaf2bh@bosch.com/.ucx/logs/002-apply-permissions-to-backup-groups/run-998401839628583/apply_permissions_to_backup_groups.log` locally to troubleshoot with more details. Timed out after 0:05:00
13:31:07 DEBUG [databricks] {MainThread} Task crash details
Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/retries.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/core.py", line 1202, in _perform
    raise self._make_nicer_error(response=response, **payload) from None
databricks.sdk.core.DatabricksError: The service at /api/2.0/preview/scim/v2/Groups is taking too long to process your request. Please try again later or try a faster operation. [TraceId: 00-6181f2b048d1614d566891b49906f4f2-ea4612ebad49aba1-00]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/tasks.py", line 149, in trigger
    current_task.fn(cfg)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/runtime.py", line 368, in apply_permissions_to_backup_groups
    group_manager.prepare_groups_in_environment()
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/workspace_access/groups.py", line 208, in prepare_groups_in_environment
    self._set_migration_groups_with_backup(valid_group_names)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/workspace_access/groups.py", line 326, in _set_migration_groups_with_backup
    backup_group = self._get_or_create_backup_group(source_group_name=name, source_group=ws_group)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/retries.py", line 47, in wrapper
    raise err
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/retries.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/mixins/hardening.py", line 57, in wrapper
    return func(*args, **kwargs)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/workspace_access/groups.py", line 308, in _get_or_create_backup_group
    backup_group = self._ws.groups.create(
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/service/iam.py", line 1833, in create
    res = self._api.do('POST', '/api/2.0/preview/scim/v2/Groups', body=body, headers=headers)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/core.py", line 1110, in do
    return retryable(self._perform)(method,
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/retries.py", line 52, in wrapper
    raise TimeoutError(f'Timed out after {timeout}') from last_err
TimeoutError: Timed out after 0:05:00
```

**Comment by nfx** [comment]
The presence of "TimeoutError: Timed out after 0:05:00" means we're handling it, and it's the platform not sending correct headers back.

**Comment by pohlposition** [comment]
Should be fixed with API / SDK release

**Comment by pohlposition** [comment]
@nfx , is this fixed in the last release?
