### ISSUE TITLE
apply backup group permissions task failed: 'str' object has no attribute 'value'

### ISSUE THREAD

**Issue by fannijako** [databrickslabs/ucx#559]
```
16:26:11 DEBUG [databricks.sdk] {ThreadPoolExecutor-0_3} POST /api/2.0/preview/sql/permissions/alerts/fb48558f-3a58-4818-98f8-3b9a0090edee
> {
>   "access_control_list": [
>     {
>       "permission_level": "CAN_MANAGE",
>       "user_name": "dbd8fe@bosch.com"
>     },
>     {
>       "group_name": "db-temp-idm2bcd_dssi03prod_dqmstudy2_dev",
>       "permission_level": "CAN_RUN"
>     },
>     "... (1 additional elements)"
>   ]
> }
< 200 OK
< {
<   "access_control_list": [
<     {
<       "permission_level": "CAN_MANAGE",
<       "user_name": "dbd8fe@bosch.com"
<     },
<     {
<       "group_name": "db-temp-idm2bcd_dssi03prod_dqmstudy2_dev",
<       "permission_level": "CAN_RUN"
<     },
<     "... (1 additional elements)"
<   ],
<   "object_id": "alerts/fb48558f-3a58-4818-98f8-3b9a0090edee",
<   "object_type": "alert"
< }
16:26:11 ERROR [databricks.labs.ucx.framework.parallel] {ThreadPoolExecutor-0_3} apply backup group permissions task failed: 'str' object has no attribute 'value'
Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/parallel.py", line 108, in inner
    return func(*args, **kwargs), None
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/mixins/hardening.py", line 57, in wrapper
    return func(*args, **kwargs)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/workspace_access/redash.py", line 140, in _applier_task
    return retried_check(object_id, object_id, acl)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/retries.py", line 47, in wrapper
    raise err
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/retries.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/workspace_access/redash.py", line 114, in _inflight_check
    remote_permission = self._safe_get_dbsql_permissions(object_type, object_id)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/workspace_access/redash.py", line 92, in _safe_get_dbsql_permissions
    return self._ws.dbsql_permissions.get(object_type, object_id)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/service/sql.py", line 2890, in get
    f'/api/2.0/preview/sql/permissions/{object_type.value}/{object_id}',
AttributeError: 'str' object has no attribute 'value'
```

```
16:26:13 DEBUG [databricks.sdk] {ThreadPoolExecutor-0_6} POST /api/2.0/preview/sql/permissions/dashboards/74a7617d-f6d0-4516-95f6-de374a624c36
> {
>   "access_control_list": [
>     {
>       "permission_level": "CAN_MANAGE",
>       "user_name": "dbd8fe@bosch.com"
>     },
>     {
>       "group_name": "db-temp-idm2bcd_dssi03prod_dqmstudy2_dev",
>       "permission_level": "CAN_VIEW"
>     },
>     "... (1 additional elements)"
>   ]
> }
< 200 OK
< {
<   "access_control_list": [
<     {
<       "permission_level": "CAN_MANAGE",
<       "user_name": "dbd8fe@bosch.com"
<     },
<     {
<       "group_name": "db-temp-idm2bcd_dssi03prod_dqmstudy2_dev",
<       "permission_level": "CAN_VIEW"
<     },
<     "... (1 additional elements)"
<   ],
<   "object_id": "dashboards/74a7617d-f6d0-4516-95f6-de374a624c36",
<   "object_type": "dashboard"
< }
16:26:13 ERROR [databricks.labs.ucx.framework.parallel] {ThreadPoolExecutor-0_6} apply backup group permissions task failed: 'str' object has no attribute 'value'
Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/parallel.py", line 108, in inner
    return func(*args, **kwargs), None
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/mixins/hardening.py", line 57, in wrapper
    return func(*args, **kwargs)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/workspace_access/redash.py", line 140, in _applier_task
    return retried_check(object_id, object_id, acl)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/retries.py", line 47, in wrapper
    raise err
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/retries.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/workspace_access/redash.py", line 114, in _inflight_check
    remote_permission = self._safe_get_dbsql_permissions(object_type, object_id)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/workspace_access/redash.py", line 92, in _safe_get_dbsql_permissions
    return self._ws.dbsql_permissions.get(object_type, object_id)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/service/sql.py", line 2890, in get
    f'/api/2.0/preview/sql/permissions/{object_type.value}/{object_id}',
AttributeError: 'str' object has no attribute 'value'
```

```
16:26:16 DEBUG [databricks.sdk] {ThreadPoolExecutor-0_5} POST /api/2.0/preview/sql/permissions/queries/219e03b0-7270-4545-8156-0377770ce06d
> {
>   "access_control_list": [
>     {
>       "permission_level": "CAN_MANAGE",
>       "user_name": "dbd8fe@bosch.com"
>     },
>     {
>       "group_name": "db-temp-idm2bcd_dssi03prod_dqmstudy2_dev",
>       "permission_level": "CAN_VIEW"
>     },
>     "... (1 additional elements)"
>   ]
> }
< 200 OK
< {
<   "access_control_list": [
<     {
<       "permission_level": "CAN_MANAGE",
<       "user_name": "dbd8fe@bosch.com"
<     },
<     {
<       "group_name": "db-temp-idm2bcd_dssi03prod_dqmstudy2_dev",
<       "permission_level": "CAN_VIEW"
<     },
<     "... (1 additional elements)"
<   ],
<   "object_id": "queries/219e03b0-7270-4545-8156-0377770ce06d",
<   "object_type": "query"
< }
16:26:16 ERROR [databricks.labs.ucx.framework.parallel] {ThreadPoolExecutor-0_5} apply backup group permissions task failed: 'str' object has no attribute 'value'
Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/parallel.py", line 108, in inner
    return func(*args, **kwargs), None
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/mixins/hardening.py", line 57, in wrapper
    return func(*args, **kwargs)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/workspace_access/redash.py", line 140, in _applier_task
    return retried_check(object_id, object_id, acl)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/retries.py", line 47, in wrapper
    raise err
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/retries.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/workspace_access/redash.py", line 114, in _inflight_check
    remote_permission = self._safe_get_dbsql_permissions(object_type, object_id)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/workspace_access/redash.py", line 92, in _safe_get_dbsql_permissions
    return self._ws.dbsql_permissions.get(object_type, object_id)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/service/sql.py", line 2890, in get
    f'/api/2.0/preview/sql/permissions/{object_type.value}/{object_id}',
AttributeError: 'str' object has no attribute 'value'
```

**Comment by nfx** [comment]
@william-conti did you integration test this? 😉

**Comment by FastLee** [comment]
I'll take a look at that.

**Comment by pohlposition** [comment]
@FastLee , did our last release fix this?
