### ISSUE TITLE
replace_workspace_groups_with_account_groups job failed

### ISSUE THREAD

**Issue by dipankarkush-db** [databrickslabs/ucx#580]
replace_workspace_groups_with_account_groups job failed with table or view `hive_metastore`.`ucx`.`migration_state` cannot be found.

Stack trace below - 

```
< 200 OK
< {
<   "itemsPerPage": 0,
<   "schemas": [
<     "urn:ietf:params:scim:api:messages:2.0:ListResponse"
<   ],
<   "startIndex": 33,
<   "totalResults": 32
< }
13:05:45 INFO [databricks.labs.ucx.workspace_access.groups] {MainThread} Found 22 workspace groups
13:05:45 DEBUG [databricks.labs.ucx.framework.crawlers] {MainThread} [spark][fetch] SELECT * FROM hive_metastore.ucx.migration_state
13:05:45 ERROR [databricks.labs.ucx] {MainThread} Task crashed. Execute `databricks workspace export /Users/abc@def.com/.ucx/logs/003-replace-workspace-local-with-account-groups/run-123456789/replace_workspace_groups_with_account_groups.log` locally to troubleshoot with more details. [TABLE_OR_VIEW_NOT_FOUND] The table or view `hive_metastore`.`ucx`.`migration_state` cannot be found. Verify the spelling and correctness of the schema and catalog.
If you did not qualify the name with a schema, verify the current_schema() output, or qualify the name with the correct schema and catalog.
To tolerate the error on drop use DROP VIEW IF EXISTS or DROP TABLE IF EXISTS.; line 1 pos 14;
'Project [*]
+- 'UnresolvedRelation [hive_metastore, ucx, migration_state], [], false

13:05:45 DEBUG [databricks] {MainThread} Task crash details
Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/tasks.py", line 149, in trigger
    current_task.fn(cfg)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/runtime.py", line 391, in replace_workspace_groups_with_account_groups
    remote_state = GroupMigrationState().fetch_migration_state(RuntimeBackend(), cfg.inventory_database)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/workspace_access/groups.py", line 83, in fetch_migration_state
    migration_group_infos = backend.fetch(f"SELECT * FROM hive_metastore.{inventory_database}.migration_state")
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/crawlers.py", line 137, in fetch
    return self._spark.sql(sql).collect()
  File "/databricks/spark/python/pyspark/instrumentation_utils.py", line 48, in wrapper
    res = func(*args, **kwargs)
  File "/databricks/spark/python/pyspark/sql/session.py", line 1602, in sql
    return DataFrame(self._jsparkSession.sql(sqlQuery, litArgs), self)
  File "/databricks/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
  File "/databricks/spark/python/pyspark/errors/exceptions/captured.py", line 194, in deco
    raise converted from None
pyspark.errors.exceptions.captured.AnalysisException: [TABLE_OR_VIEW_NOT_FOUND] The table or view `hive_metastore`.`ucx`.`migration_state` cannot be found. Verify the spelling and correctness of the schema and catalog.
If you did not qualify the name with a schema, verify the current_schema() output, or qualify the name with the correct schema and catalog.
To tolerate the error on drop use DROP VIEW IF EXISTS or DROP TABLE IF EXISTS.; line 1 pos 14;
'Project [*]
+- 'UnresolvedRelation [hive_metastore, ucx, migration_state], [], false

```

**Comment by nfx** [comment]
Please upgrade to the latest version. It seems that the version you're referring is too old.
