### ISSUE TITLE
0.0.6 install.sh fails

### ISSUE THREAD

**Issue by dmoore247** [databrickslabs/ucx#599]
Expected `install.sh` to start prompting me but instead it fails right out of the gate

To reproduce:
```
git clone https://github.com/databrickslabs/ucx

ucx % export DATABRICKS_CONFIG_PROFILE=HLSFIELD
ucx % bash ./install.sh 
[i] found Python 3.9.6 -> /usr/bin/python3
[i] found Python 3.10.10 -> /Users/douglas.moore/.pyenv/shims/python3
[i] latest python is /Users/douglas.moore/.pyenv/shims/python3
[i] installing venv into: /var/folders/d6/5qdmg6pn5kgbnnjcgpg0lxwr0000gp/T/tmp.SYLQ2ywr
[+] making sure we have the latest pip version
[+] installing dependencies within ephemeral Virtualenv: /var/folders/d6/5qdmg6pn5kgbnnjcgpg0lxwr0000gp/T/tmp.SYLQ2ywr
Traceback (most recent call last):
  File "/Users/douglas.moore/.pyenv/versions/3.10.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/douglas.moore/.pyenv/versions/3.10.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/douglas.moore/development/ucx/src/databricks/labs/ucx/install.py", line 908, in <module>
    installer.run()
  File "/Users/douglas.moore/development/ucx/src/databricks/labs/ucx/install.py", line 149, in run
    logger.info(f"Installing UCX v{self._version}")
  File "/Users/douglas.moore/development/ucx/src/databricks/labs/ucx/install.py", line 795, in _version
    raise OSError(msg) from None
OSError: Cannot determine unreleased version. Please report this error message that you see on https://github.com/databrickslabs/ucx/issues/new. Meanwhile, download, unpack, and install the latest released version from https://github.com/databrickslabs/ucx/releases. Original error is: 'NoneType' object has no attribute 'split'
```

**Comment by dmoore247** [comment]
Also for `make test`

```================================= short test summary info ==================================
FAILED tests/unit/test_install.py::test_build_wheel - OSError: Cannot determine unreleased version. Please report this error message that you...
FAILED tests/unit/test_install.py::test_main_with_existing_conf_does_not_recreate_config - OSError: Cannot determine unreleased version. Please report this error message that you...
FAILED tests/unit/test_install.py::test_replace_clusters_for_integration_tests - OSError: Cannot determine unreleased version. Please report this error message that you...
============================== 3 failed, 247 passed in 5.29s ===============================
```

**Comment by dmoore247** [comment]
This line of code, `pre_release` is `None`
<img width="728" alt="image" src="https://github.com/databrickslabs/ucx/assets/1122251/76bcc059-edd4-41c5-9cb6-9db2cc164f30">
