### ISSUE TITLE
[TABLE_OR_VIEW_NOT_FOUND] The table or view `ucx`.`workspace_objects` cannot be found

### ISSUE THREAD

**Issue by Arnovda** [databrickslabs/ucx#609]
![Screenshot 2023-11-20 141915](https://github.com/databrickslabs/ucx/assets/62990190/60b02b25-170d-483f-93f5-97f15b6b03c2)
I am not able to generate the necessary tables inside of the hive-metastore.
Only 'mounts', 'table_failures' and' tables' are made in catalog 'ucx'.
This is the error when trying to create the other tables when running the job '[UCX] assessment':

13:07:17 INFO [databricks.labs.ucx] {MainThread} After job finishes, see debug logs at /Workspace/Users/arno.vandenaudenaerde@element61.be/.ucx/logs/assessment/run-511304491579397/workspace_listing.log
13:07:17 DEBUG [databricks.sdk] {MainThread} /root/.databrickscfg does not exist
13:07:17 DEBUG [databricks.sdk] {MainThread} Attempting to configure auth: pat
13:07:17 DEBUG [databricks.sdk] {MainThread} Attempting to configure auth: basic
13:07:17 DEBUG [databricks.sdk] {MainThread} Attempting to configure auth: metadata-service
13:07:17 DEBUG [databricks.sdk] {MainThread} Attempting to configure auth: oauth-m2m
13:07:17 DEBUG [databricks.sdk] {MainThread} Attempting to configure auth: azure-client-secret
13:07:17 DEBUG [databricks.sdk] {MainThread} Attempting to configure auth: github-oidc-azure
13:07:17 DEBUG [databricks.sdk] {MainThread} Attempting to configure auth: azure-cli
13:07:17 DEBUG [databricks.sdk] {MainThread} Attempting to configure auth: external-browser
13:07:17 DEBUG [databricks.sdk] {MainThread} Attempting to configure auth: databricks-cli
13:07:17 DEBUG [databricks.sdk] {MainThread} Attempting to configure auth: runtime
13:07:17 DEBUG [databricks.sdk] {MainThread} runtime SDK credential provider available
13:07:17 DEBUG [databricks.sdk] {MainThread} [init_runtime_native_auth] runtime native auth configured
13:07:17 DEBUG [databricks.labs.ucx.framework.crawlers] {MainThread} [hive_metastore.ucx.workspace_objects] fetching workspace_objects inventory
13:07:17 DEBUG [databricks.labs.ucx.framework.crawlers] {MainThread} [spark][fetch] SELECT * FROM ucx.workspace_objects
13:07:19 ERROR [databricks.labs.ucx] {MainThread} Task crashed. Execute `databricks workspace export /Users/arno.vandenaudenaerde@element61.be/.ucx/logs/assessment/run-511304491579397/workspace_listing.log` locally to troubleshoot with more details. [TABLE_OR_VIEW_NOT_FOUND] The table or view `ucx`.`workspace_objects` cannot be found. Verify the spelling and correctness of the schema and catalog.
If you did not qualify the name with a schema, verify the current_schema() output, or qualify the name with the correct schema and catalog.
To tolerate the error on drop use DROP VIEW IF EXISTS or DROP TABLE IF EXISTS.; line 1 pos 14;
'Project [*]
+- 'UnresolvedRelation [ucx, workspace_objects], [], false

13:07:19 DEBUG [databricks] {MainThread} Task crash details
Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/tasks.py", line 149, in trigger
    current_task.fn(cfg)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/runtime.py", line 172, in workspace_listing
    crawler.snapshot()
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/workspace_access/generic.py", line 305, in snapshot
    return self._snapshot(self._try_fetch, self._crawl)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/crawlers.py", line 235, in _snapshot
    cached_results = list(fetcher())
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/workspace_access/generic.py", line 308, in _try_fetch
    for row in self._fetch(f"SELECT * FROM {self._schema}.{self._table}"):
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/crawlers.py", line 139, in fetch
    return self._spark.sql(sql).collect()
  File "/databricks/spark/python/pyspark/instrumentation_utils.py", line 47, in wrapper
    res = func(*args, **kwargs)
  File "/databricks/spark/python/pyspark/sql/session.py", line 1702, in sql
    return DataFrame(self._jsparkSession.sql(sqlQuery, litArgs), self)
  File "/databricks/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
  File "/databricks/spark/python/pyspark/errors/exceptions/captured.py", line 194, in deco
    raise converted from None
pyspark.errors.exceptions.captured.AnalysisException: [TABLE_OR_VIEW_NOT_FOUND] The table or view `ucx`.`workspace_objects` cannot be found. Verify the spelling and correctness of the schema and catalog.
If you did not qualify the name with a schema, verify the current_schema() output, or qualify the name with the correct schema and catalog.
To tolerate the error on drop use DROP VIEW IF EXISTS or DROP TABLE IF EXISTS.; line 1 pos 14;
'Project [*]
+- 'UnresolvedRelation [ucx, workspace_objects], [], false

Thanks for the help!

**Comment by JCZuurmond** [comment]
@nfx : I run into this issue in the latest `v0.6.2`, looking at the closed issues it looked like it was resolved. I did not run into the issue when using `v0.6.1`, for me it looks like the latest minor release reintroduced this issue
