### ISSUE TITLE
Apply redash permissions fails with AttributeError: 'str' object has no attribute 'value'

### ISSUE THREAD

**Issue by william-conti** [databrickslabs/ucx#626]
In apply_permissions_to_account_groups, all apply tasks related to dbsql objects failed with the similar error message:

```
17:30:18 DEBUG [databricks.sdk] {ThreadPoolExecutor-0_2} POST /api/2.0/preview/sql/permissions/dashboards/527b7d1c-6bb8-4737-aecc-59525f839546
> {
>   "access_control_list": [
>     {
>       "permission_level": "CAN_MANAGE",
>       "user_name": "dd78bc9b-e2f0-4d26-bdd0-0ad7c3aecc9a"
>     },
>     {
>       "group_name": "ucx_8oPt",
>       "permission_level": "CAN_VIEW"
>     },
>     "... (21 additional elements)"
>   ]
> }
< 200 OK
< {
<   "access_control_list": [
<     {
<       "permission_level": "CAN_MANAGE",
<       "user_name": "dd78bc9b-e2f0-4d26-bdd0-0ad7c3aecc9a"
<     },
<     {
<       "group_name": "ucx_Na8U",
<       "permission_level": "CAN_MANAGE"
<     },
<     "... (21 additional elements)"
<   ],
<   "object_id": "dashboards/527b7d1c-6bb8-4737-aecc-59525f839546",
<   "object_type": "dashboard"
< }
17:30:18 ERROR [databricks.labs.ucx.framework.parallel] {ThreadPoolExecutor-0_2} apply account group permissions task failed: 'str' object has no attribute 'value'
Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/parallel.py", line 108, in inner
    return func(*args, **kwargs), None
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/mixins/hardening.py", line 57, in wrapper
    return func(*args, **kwargs)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/workspace_access/redash.py", line 132, in _applier_task
    return retried_check(object_id, object_id, acl)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/retries.py", line 47, in wrapper
    raise err
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/retries.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/workspace_access/redash.py", line 106, in _inflight_check
    remote_permission = self._safe_get_dbsql_permissions(object_type, object_id)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/workspace_access/redash.py", line 84, in _safe_get_dbsql_permissions
    return self._ws.dbsql_permissions.get(object_type, object_id)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/service/sql.py", line 2890, in get
    f'/api/2.0/preview/sql/permissions/{object_type.value}/{object_id}',
AttributeError: 'str' object has no attribute 'value'
```

**Comment by nfx** [comment]
Thank you for the feature request! Currently, the team operates in a limited capacity, carefully prioritizing, and we cannot provide a timeline to implement this feature. Please make a Pull Request if you'd like to see this feature sooner, and we'll guide you through the journey.
