### ISSUE TITLE
Secret scope apply task always raises ValueError

### ISSUE THREAD

**Issue by william-conti** [databrickslabs/ucx#627]
All apply_tasks for secret scopes eventually fails because the inflight check throws ValueError

```
17:33:17 DEBUG [databricks.sdk] {ThreadPoolExecutor-0_3} GET /api/2.0/secrets/acls/list?scope=sdk-5cdD
< 200 OK
< {
<   "items": [
<     {
<       "permission": "MANAGE",
<       "principal": "db-temp-ucx_WVGd"
<     },
<     {
<       "permission": "WRITE",
<       "principal": "db-temp-ucx_a9OW"
<     },
<     "... (21 additional elements)"
<   ]
< }
17:33:17 DEBUG [databricks.sdk] {ThreadPoolExecutor-0_3} Retrying: ValueError is allowed to retry (sleeping ~2s)
17:33:17 ERROR [databricks.labs.ucx.framework.parallel] {ThreadPoolExecutor-0_1} apply account group permissions task failed: Timed out after 0:01:00
Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/retries.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/workspace_access/secrets.py", line 83, in _inflight_check
    raise ValueError(msg)
ValueError: Applied permission None is not equal to expected permission AclPermission.READ

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/parallel.py", line 108, in inner
    return func(*args, **kwargs), None
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/workspace_access/secrets.py", line 60, in apply_acls
    self._rate_limited_put_acl(item.object_id, acl.principal, acl.permission)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/mixins/hardening.py", line 57, in wrapper
    return func(*args, **kwargs)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/workspace_access/secrets.py", line 91, in _rate_limited_put_acl
    retried_check(object_id, principal, permission)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/retries.py", line 52, in wrapper
    raise TimeoutError(f'Timed out after {timeout}') from last_err
TimeoutError: Timed out after 0:01:00
```

**Comment by nfx** [comment]
Thank you for the feature request! Currently, the team operates in a limited capacity, carefully prioritizing, and we cannot provide a timeline to implement this feature. Please make a Pull Request if you'd like to see this feature sooner, and we'll guide you through the journey.

**Comment by william-conti** [comment]
After further investigation, it seems that the code has successfully applied the permission to the account group. But when listing the acls in the secret scope, it seems that the permissions weren't actually applied:

```
10:56:11 DEBUG [databricks.sdk] {apply_account_group_permissions_5} POST /api/2.0/secrets/acls/put
> {
>   "permission": "WRITE",
>   "principal": "ucx_j2Yn",
>   "scope": "sdk-83LU"
> }
< 200 OK
< {}
10:56:11 DEBUG [databricks.sdk] {apply_account_group_permissions_5} Retrying: ValueError is allowed to retry (sleeping ~1s)
10:56:11 DEBUG [databricks.sdk] {apply_account_group_permissions_5} GET /api/2.0/secrets/acls/list?scope=sdk-83LU
< 200 OK
< {
<   "items": [
<     {
<       "permission": "WRITE",
<       "principal": "db-temp-ucx_j2Yn"
<     },
<     {
<       "permission": "READ",
<       "principal": "db-temp-ucx_dm8i"
<     },
<     "... (8 additional elements)"
<   ]
< }
10:56:13 DEBUG [databricks.sdk] {apply_account_group_permissions_5} GET /api/2.0/secrets/acls/list?scope=sdk-83LU
< 200 OK
< {
<   "items": [
<     {
<       "permission": "WRITE",
<       "principal": "db-temp-ucx_j2Yn"
<     },
<     {
<       "permission": "READ",
<       "principal": "db-temp-ucx_dm8i"
<     },
<     "... (8 additional elements)"
<   ]
< }
10:57:02 DEBUG [databricks.sdk] {apply_account_group_permissions_5} GET /api/2.0/secrets/acls/list?scope=sdk-83LU
< 200 OK
< {
<   "items": [
<     {
<       "permission": "WRITE",
<       "principal": "db-temp-ucx_j2Yn"
<     },
<     {
<       "permission": "READ",
<       "principal": "db-temp-ucx_dm8i"
<     },
<     "... (8 additional elements)"
<   ]
< }
10:57:02 DEBUG [databricks.sdk] {apply_account_group_permissions_5} Retrying: ValueError is allowed to retry (sleeping ~10s)
10:57:12 ERROR [databricks.labs.ucx.framework.parallel] {apply_account_group_permissions_5} apply account group permissions task failed: Timed out after 0:01:00
Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/retries.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/workspace_access/secrets.py", line 83, in _inflight_check
    raise ValueError(msg)
ValueError: Applied permission None is not equal to expected permission AclPermission.WRITE

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/parallel.py", line 110, in inner
    return func(*args, **kwargs), None
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/workspace_access/secrets.py", line 60, in apply_acls
    self._rate_limited_put_acl(item.object_id, acl.principal, acl.permission)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/mixins/hardening.py", line 57, in wrapper
    return func(*args, **kwargs)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/workspace_access/secrets.py", line 91, in _rate_limited_put_acl
    retried_check(object_id, principal, permission)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/retries.py", line 52, in wrapper
    raise TimeoutError(f'Timed out after {timeout}') from last_err
```
