### ISSUE TITLE
Schema ownership is not properly applied to account group

### ISSUE THREAD

**Issue by william-conti** [databrickslabs/ucx#628]
When transfering the ownership on a database hive_metastore from ws group to account group, code fail with a TABLE_OR_VIEW_NOT_FOUND exception

```
19:36:30 DEBUG [databricks.labs.ucx.framework.crawlers] {ThreadPoolExecutor-0_0} [spark][execute] ALTER hive_metastore.ucx_s6tzy OWNER TO `ucx_eybT`
19:36:30 ERROR [databricks.labs.ucx.framework.parallel] {ThreadPoolExecutor-0_0} apply account group permissions task failed: [TABLE_OR_VIEW_NOT_FOUND] The table or view `spark_catalog`.`hive_metastore`.`ucx_s6tzy` cannot be found. Verify the spelling and correctness of the schema and catalog.
If you did not qualify the name with a schema, verify the current_schema() output, or qualify the name with the correct schema and catalog.
To tolerate the error on drop use DROP VIEW IF EXISTS or DROP TABLE IF EXISTS.;
ChangeOwnerCommand com.databricks.sql.acl.ReflectionBackedAclClient@5553ec94, Table(`spark_catalog`.`hive_metastore`.`ucx_s6tzy`), ucx_eybT
Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/parallel.py", line 108, in inner
    return func(*args, **kwargs), None
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/crawlers.py", line 135, in execute
    self._spark.sql(sql)
  File "/databricks/spark/python/pyspark/instrumentation_utils.py", line 48, in wrapper
    res = func(*args, **kwargs)
  File "/databricks/spark/python/pyspark/sql/session.py", line 1702, in sql
    return DataFrame(self._jsparkSession.sql(sqlQuery, litArgs), self)
  File "/databricks/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
  File "/databricks/spark/python/pyspark/errors/exceptions/captured.py", line 194, in deco
    raise converted from None
pyspark.errors.exceptions.captured.AnalysisException: [TABLE_OR_VIEW_NOT_FOUND] The table or view `spark_catalog`.`hive_metastore`.`ucx_s6tzy` cannot be found. Verify the spelling and correctness of the schema and catalog.
If you did not qualify the name with a schema, verify the current_schema() output, or qualify the name with the correct schema and catalog.
To tolerate the error on drop use DROP VIEW IF EXISTS or DROP TABLE IF EXISTS.;
ChangeOwnerCommand com.databricks.sql.acl.ReflectionBackedAclClient@5553ec94, Table(`spark_catalog`.`hive_metastore`.`ucx_s6tzy`), ucx_eybT

```

**Comment by nfx** [comment]
Thank you for the feature request! Currently, the team operates in a limited capacity, carefully prioritizing, and we cannot provide a timeline to implement this feature. Please make a Pull Request if you'd like to see this feature sooner, and we'll guide you through the journey.
