### ISSUE TITLE
Need support installing on GCP workspaces. Encountering  Endpoint not found for /2.0/sql/statements/

### ISSUE THREAD

**Issue by girip-db** [databrickslabs/ucx#644]
Encountering below error when installing in GCP workspace

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/ucx/src/databricks/labs/ucx/install.py", line 908, in <module>
    installer.run()
  File "/ucx/src/databricks/labs/ucx/install.py", line 151, in run
    self._run_configured()
  File "/ucx/src/databricks/labs/ucx/install.py", line 157, in _run_configured
    self._create_database()
  File "/ucx/src/databricks/labs/ucx/install.py", line 165, in _create_database
    deploy_schema(self._sql_backend, self._current_config.inventory_database)
  File "/ucx/src/databricks/labs/ucx/install.py", line 114, in deploy_schema
    deployer.deploy_schema()
  File "/ucx/src/databricks/labs/ucx/framework/crawlers.py", line 258, in deploy_schema
    self._sql_backend.execute(f"CREATE SCHEMA IF NOT EXISTS hive_metastore.{self._inventory_schema}")
  File "/ucx/src/databricks/labs/ucx/framework/crawlers.py", line 81, in execute
    self._sql.execute(self._warehouse_id, sql)
  File "/ucx/src/databricks/labs/ucx/mixins/sql.py", line 141, in execute
    immediate_response = self.execute_statement(
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/xk/qxv10msx4hq5sz5fj4jvdz1h0000gp/T/tmp.fTlJTwWD/lib/python3.11/site-packages/databricks/sdk/service/sql.py", line 3541, in execute_statement
    res = self._api.do('POST', '/api/2.0/sql/statements/', body=body, headers=headers)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/xk/qxv10msx4hq5sz5fj4jvdz1h0000gp/T/tmp.fTlJTwWD/lib/python3.11/site-packages/databricks/sdk/core.py", line 1070, in do
    return retryable(self._perform)(method,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/xk/qxv10msx4hq5sz5fj4jvdz1h0000gp/T/tmp.fTlJTwWD/lib/python3.11/site-packages/databricks/sdk/retries.py", line 47, in wrapper
    raise err
  File "/private/var/folders/xk/qxv10msx4hq5sz5fj4jvdz1h0000gp/T/tmp.fTlJTwWD/lib/python3.11/site-packages/databricks/sdk/retries.py", line 29, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/xk/qxv10msx4hq5sz5fj4jvdz1h0000gp/T/tmp.fTlJTwWD/lib/python3.11/site-packages/databricks/sdk/core.py", line 1162, in _perform
    raise self._make_nicer_error(response=response, **payload) from None
databricks.sdk.errors.mapping.NotFound: Endpoint not found for /2.0/sql/statements/

**Comment by nfx** [comment]
our platform doesn't support cloud fetch on GCP, required for statement execution API.
