### ISSUE TITLE
Assessment workflow: Crawl permissions timeout exception

### ISSUE THREAD

**Issue by anjalijain-db** [databrickslabs/ucx#709]
When trying to run the assessment report it failed due to time out exception . Exception raised in crawl_permissions.

Below is the error:
<img width="1142" alt="image" src="https://github.com/databrickslabs/ucx/assets/153831300/2c53e694-602e-4772-8f8a-134b7b4c7d2a">

**Comment by nfx** [comment]
@anjalijain-db Please share the full log - we need to know which part of the code threw this error

**Comment by anjalijain-db** [comment]
**ERROR 1:** 
08:04:31 DEBUG [databricks.sdk] {crawl_permissions_4} GET /api/2.0/permissions/notebooks/231500453608099
< 500 Internal Server Error
< {
<   "error_code": "INTERNAL_ERROR",
<   "message": "java.io.IOException: java.util.concurrent.TimeoutException: Timed out after 5 seconds"
< }
08:04:31 ERROR [databricks.labs.ucx.framework.parallel] {crawl_permissions_4} crawl permissions task failed: java.io.IOException: java.util.concurrent.TimeoutException: Timed out after 5 seconds
Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/parallel.py", line 121, in inner
    return func(*args, **kwargs), None
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/mixins/hardening.py", line 57, in wrapper
    return func(*args, **kwargs)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/workspace_access/generic.py", line 146, in _crawler_task
    permissions = self._safe_get_permissions(object_type, object_id)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/workspace_access/generic.py", line 220, in _safe_get_permissions
    return self._ws.permissions.get(object_type, object_id)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/service/iam.py", line 2413, in get
    res = self._api.do('GET',
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/core.py", line 1144, in do
    return retryable(self._perform)(method,
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/retries.py", line 47, in wrapper
    raise err
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/retries.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/core.py", line 1236, in _perform
    raise self._make_nicer_error(response=response, **payload) from None
databricks.sdk.errors.mapping.InternalError: java.io.IOException: java.util.concurrent.TimeoutException: Timed out after 5 seconds

--------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------

**ERROR 2:** 
07:52:46 ERROR [databricks.labs.ucx.framework.parallel] {crawl_permissions_3} crawl permissions task failed: java.io.IOException: java.util.concurrent.TimeoutException: Timed out after 5 seconds
Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/parallel.py", line 121, in inner
    return func(*args, **kwargs), None
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/mixins/hardening.py", line 57, in wrapper
    return func(*args, **kwargs)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/workspace_access/generic.py", line 146, in _crawler_task
    permissions = self._safe_get_permissions(object_type, object_id)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/workspace_access/generic.py", line 220, in _safe_get_permissions
    return self._ws.permissions.get(object_type, object_id)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/service/iam.py", line 2413, in get
    res = self._api.do('GET',
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/core.py", line 1144, in do
    return retryable(self._perform)(method,
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/retries.py", line 47, in wrapper
    raise err
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/retries.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/core.py", line 1236, in _perform
    raise self._make_nicer_error(response=response, **payload) from None
databricks.sdk.errors.mapping.InternalError: java.io.IOException: java.util.concurrent.TimeoutException: Timed out after 5 seconds
07:52:46 DEBUG [databricks.sdk] {crawl_permissions_5} GET /api/2.0/permissions/notebooks/231500453602730

**Comment by anjalijain-db** [comment]
@nfx  I have raised a PR to resolve this timeout issue. Kindly review and approve.

**Comment by nfx** [comment]
Following up - is this issue still relevant?
