### ISSUE TITLE
[BUG]: guess_external_locations task fails

### ISSUE THREAD

**Issue by pritishpai** [databrickslabs/ucx#798]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Customer recently installed latest version on their AWS databricks installing it from CLI on a Ubuntu WSL. I was able to reproduce this issue on my macOS and field-eng-east Azure on latest version (0.9.0) and (0.8.0). guess_external_location fails with the same error.

### Steps To Reproduce

1. Install UCX from cli
2. Run the assessment step

### Cloud

Azure

### Operating System

macOS

### Version

latest via Databricks CLI

### Relevant log output

```shell
17:04:19 INFO [databricks.labs.ucx] {MainThread} UCX v0.8.0 After job finishes, see debug logs at /Workspace/Users/pritish.pai@databricks.com/.ucx/logs/assessment/run-994898146268997/guess_external_locations.log
17:04:19 DEBUG [databricks.sdk] {MainThread} /root/.databrickscfg does not exist
17:04:19 DEBUG [databricks.sdk] {MainThread} Attempting to configure auth: pat
17:04:19 DEBUG [databricks.sdk] {MainThread} Attempting to configure auth: basic
17:04:19 DEBUG [databricks.sdk] {MainThread} Attempting to configure auth: metadata-service
17:04:19 DEBUG [databricks.sdk] {MainThread} Attempting to configure auth: oauth-m2m
17:04:19 DEBUG [databricks.sdk] {MainThread} Attempting to configure auth: azure-client-secret
17:04:19 DEBUG [databricks.sdk] {MainThread} Attempting to configure auth: github-oidc-azure
17:04:19 DEBUG [databricks.sdk] {MainThread} Attempting to configure auth: azure-cli
17:04:19 DEBUG [databricks.sdk] {MainThread} Attempting to configure auth: external-browser
17:04:19 DEBUG [databricks.sdk] {MainThread} Attempting to configure auth: databricks-cli
17:04:19 DEBUG [databricks.sdk] {MainThread} Attempting to configure auth: runtime
17:04:19 DEBUG [databricks.sdk] {MainThread} runtime SDK credential provider available
17:04:19 DEBUG [databricks.sdk] {MainThread} [init_runtime_native_auth] runtime native auth configured
17:04:19 DEBUG [databricks.labs.ucx.framework.crawlers] {MainThread} [hive_metastore.ucx_ppai.external_locations] fetching external_locations inventory
17:04:19 DEBUG [databricks.labs.ucx.framework.crawlers] {MainThread} [spark][fetch] SELECT * FROM ucx_ppai.external_locations
17:04:20 ERROR [databricks.labs.ucx] {MainThread} Task crashed. Execute `databricks workspace export /Users/pritish.pai@databricks.com/.ucx/logs/assessment/run-994898146268997/guess_external_locations.log` locally to troubleshoot with more details. ExternalLocation.__init__() missing 1 required positional argument: 'table_count'
17:04:20 DEBUG [databricks] {MainThread} Task crash details
Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/tasks.py", line 179, in trigger
    current_task.fn(cfg)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/runtime.py", line 83, in guess_external_locations
    crawler.snapshot()
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/hive_metastore/locations.py", line 121, in snapshot
    return self._snapshot(self._try_fetch, self._external_location_list)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/crawlers.py", line 254, in _snapshot
    cached_results = list(fetcher())
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/hive_metastore/locations.py", line 125, in _try_fetch
    yield ExternalLocation(*row)
TypeError: ExternalLocation.__init__() missing 1 required positional argument: 'table_count'
```

**Comment by pritishpai** [comment]
> Can you uninstall UCX and install it again? Looks related to a schema change

Yes, it was related to the recent schema change. Liran helped me with it.
