### ISSUE TITLE
[BUG]: ModuleNotFoundError: No module named 'databricks.labs.blueprint' with `databricks labs install .`

### ISSUE THREAD

**Issue by dmoore247** [databrickslabs/ucx#843]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```shell
databricks labs ucx ensure-assessment-run --profile HLSFIELD
Traceback (most recent call last):
  File "/Users/douglas.moore/development/ucx/src/databricks/labs/ucx/cli.py", line 6, in <module>
    from databricks.labs.blueprint.cli import App
ModuleNotFoundError: No module named 'databricks.labs.blueprint'
Error: exit status 1
```

### Expected Behavior

The command should begin the install process without error

### Steps To Reproduce

Databricks CLI v0.212.2
Python 3.10.10
Latest git pull
`make clean dev`

### Cloud

Azure

### Operating System

macOS

### Version

latest via Databricks CLI

### Relevant log output

```shell
(ucx) first.name@MACBOOK ucx % databricks labs install . --profile HLSFIELD --debug
13:35:30  INFO start pid=50718 version=0.212.2 args="/opt/homebrew/bin/databricks, labs, install, ., --profile, HLSFIELD, --debug"
Installing ucx in development mode from /Users/first.name/development/ucx
13:35:30  INFO Overriding login profile: HLSFIELD pid=50718
13:35:30 DEBUG Loading HLSFIELD profile from /Users/first.name/.databrickscfg pid=50718 sdk=true
13:35:30 DEBUG Resolved login: Config: host=https://adb-9999999918558854.14.azuredatabricks.net, cluster_id=1117-233913-6w1gh5v6, account_id=deadbeef-89ba-4dd2-9161-deadbeef, token=***, profile=HLSFIELD, config_file=/Users/first.name/.databrickscfg, databricks_cli_path=/opt/homebrew/bin/databricks. Env: DATABRICKS_CLI_PATH pid=50718 sdk=true
13:35:30 DEBUG (development mode) using active virtual environment from: /Users/first.name/.pyenv/versions/3.10.10/envs/ucx pid=50718 sdk=true
13:35:30  INFO Overriding login profile: HLSFIELD pid=50718
13:35:30 DEBUG Loading HLSFIELD profile from /Users/first.name/.databrickscfg pid=50718 sdk=true
13:35:30 DEBUG Resolved login: Config: host=https://adb-9999999918558854.14.azuredatabricks.net, cluster_id=1117-233913-6w1gh5v6, account_id=deadbeef-89ba-4dd2-9161-deadbeef, token=***, profile=HLSFIELD, config_file=/Users/first.name/.databrickscfg, databricks_cli_path=/opt/homebrew/bin/databricks. Env: DATABRICKS_CLI_PATH pid=50718 sdk=true
13:35:30 DEBUG Passing down environment variables: DATABRICKS_HOST, DATABRICKS_CLUSTER_ID, DATABRICKS_ACCOUNT_ID, DATABRICKS_TOKEN, DATABRICKS_CLI_PATH pid=50718
13:35:30 DEBUG (development mode) using active virtual environment from: /Users/first.name/.pyenv/versions/3.10.10/envs/ucx pid=50718 sdk=true
13:35:30 DEBUG starting: /Users/first.name/.pyenv/versions/3.10.10/envs/ucx/bin/python3 src/databricks/labs/ucx/install.py pid=50718
Traceback (most recent call last):
  File "/Users/first.name/development/ucx/src/databricks/labs/ucx/install.py", line 15, in <module>
    from databricks.labs.blueprint.entrypoint import get_logger
ModuleNotFoundError: No module named 'databricks.labs.blueprint'
Error: exit status 1
13:35:31 ERROR failed execution pid=50718 exit_code=1 error="exit status 1"
```

**Comment by dmoore247** [comment]
Running `pip install databricks-labs-blueprint` fixes the issue and is the workaround.

**Comment by dmoore247** [comment]
Also fails with `databricks labs upgrade ucx` using databricks cli `Databricks CLI v0.212.3` for upgrading to UCX 0.11.1

**Comment by nfx** [comment]
cannot reproduce:

```
➜  ~ cd /tmp
➜  /tmp git clone https://github.com/databrickslabs/ucx.git
Cloning into 'ucx'...
remote: Enumerating objects: 9185, done.
remote: Counting objects: 100% (2939/2939), done.
remote: Compressing objects: 100% (1228/1228), done.
remote: Total 9185 (delta 1917), reused 2325 (delta 1568), pack-reused 6246
Receiving objects: 100% (9185/9185), 19.13 MiB | 2.30 MiB/s, done.
Resolving deltas: 100% (5159/5159), done.
➜  /tmp cd ucx
➜  ucx git:(main) make clean dev
rm -fr .venv clean htmlcov .mypy_cache .pytest_cache .ruff_cache .coverage coverage.xml
rm -fr **/*.pyc
...
➜  ucx git:(main) databricks labs install . --profile labs-aws-admin
Installing ucx in development mode from /tmp/ucx
13:24:28  INFO [d.l.ucx.install] Installing UCX v0.14.1+420240305132428
```

**Comment by dmoore247** [comment]
@nfx I hit this error again today, searched and found this issue :)

I started anew today:
```
mv ucx ucx.bak3
git clone ...
databricks labs install .
make test
databricks labs install .
```
make test ran as expected.

I had `databricks-labs-blueprint` installed in the virtual environment but it was down-level.

To reproduce the bug, `pip uninstall databricks-labs-blueprint`
I hit a similar error after this one because the databricks lsl module was missing.

`databricks labs install ucx` ran successfully, with the dependencies installed or not.

To better the labs install experience, adding a (databricks) python dependency check would help.

**Comment by nfx** [comment]
Run "make clean dev", it fixes the issue

**Comment by dmoore247** [comment]
@nfx 
`make clean dev` command rebuilds the python env into a hatch env which is only used with hatch commands. 

Is running `databricks labs install .` from a `hatch shell` assumed?
I could not find the advisement to use `hatch shell` for running commands. I've been using `pyenv` for command level stuff and debugging.


```
pip uninstall databricks-labs-blueprint
Found existing installation: databricks-labs-blueprint 0.4.3
Uninstalling databricks-labs-blueprint-0.4.3:
  Would remove:
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/*
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks_labs_blueprint-0.4.3.dist-info/*
  Would not remove (might be manually added):
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/connect/__init__.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/connect/auth.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/connect/cache.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/connect/debug.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/connect/py.typed
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/connect/session.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/connect/uds_channel_builder.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/labs/lsql/__about__.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/labs/lsql/__init__.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/labs/lsql/__main__.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/labs/lsql/backends.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/labs/lsql/core.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/labs/lsql/deployment.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/labs/lsql/py.typed
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/sdk/__init__.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/sdk/_widgets/__init__.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/sdk/_widgets/default_widgets_utils.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/sdk/_widgets/ipywidgets_utils.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/sdk/azure.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/sdk/casing.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/sdk/clock.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/sdk/config.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/sdk/core.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/sdk/credentials_provider.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/sdk/dbutils.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/sdk/environments.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/sdk/errors/__init__.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/sdk/errors/base.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/sdk/errors/mapper.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/sdk/errors/platform.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/sdk/errors/sdk.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/sdk/mixins/__init__.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/sdk/mixins/compute.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/sdk/mixins/files.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/sdk/mixins/workspace.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/sdk/oauth.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/sdk/py.typed
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/sdk/retries.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/sdk/runtime/__init__.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/sdk/runtime/dbutils_stub.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/sdk/service/__init__.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/sdk/service/_internal.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/sdk/service/billing.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/sdk/service/catalog.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/sdk/service/compute.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/sdk/service/dashboards.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/sdk/service/files.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/sdk/service/iam.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/sdk/service/jobs.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/sdk/service/ml.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/sdk/service/oauth2.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/sdk/service/pipelines.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/sdk/service/provisioning.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/sdk/service/serving.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/sdk/service/settings.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/sdk/service/sharing.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/sdk/service/sql.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/sdk/service/vectorsearch.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/sdk/service/workspace.py
    /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages/databricks/sdk/version.py
Proceed (Y/n)? Y
  Successfully uninstalled databricks-labs-blueprint-0.4.3
(ucx) douglas.moore@H4JD6Y7J50 ucx % databricks labs install .
Installing ucx in development mode from /Users/douglas.moore/development/ucx
Traceback (most recent call last):
  File "/Users/douglas.moore/development/ucx/src/databricks/labs/ucx/install.py", line 11, in <module>
    from databricks.labs.blueprint.entrypoint import get_logger
ModuleNotFoundError: No module named 'databricks.labs.blueprint'
Error: exit status 1
(ucx) douglas.moore@H4JD6Y7J50 ucx % databricks labs install .
(ucx) douglas.moore@H4JD6Y7J50 ucx % make clean dev
rm -fr .venv clean htmlcov .mypy_cache .pytest_cache .ruff_cache .coverage coverage.xml
rm -fr **/*.pyc
pip install hatch
Requirement already satisfied: hatch in /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages (1.7.0)
Requirement already satisfied: click>=8.0.3 in /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages (from hatch) (8.1.7)
Requirement already satisfied: hatchling>=1.14.0 in /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages (from hatch) (1.18.0)
Requirement already satisfied: httpx>=0.22.0 in /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages (from hatch) (0.25.2)
Requirement already satisfied: hyperlink>=21.0.0 in /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages (from hatch) (21.0.0)
Requirement already satisfied: keyring>=23.5.0 in /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages (from hatch) (24.3.0)
Requirement already satisfied: packaging>=21.3 in /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages (from hatch) (23.2)
Requirement already satisfied: pexpect~=4.8 in /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages (from hatch) (4.9.0)
Requirement already satisfied: platformdirs>=2.5.0 in /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages (from hatch) (4.0.0)
Requirement already satisfied: pyperclip>=1.8.2 in /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages (from hatch) (1.8.2)
Requirement already satisfied: rich>=11.2.0 in /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages (from hatch) (13.7.0)
Requirement already satisfied: shellingham>=1.4.0 in /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages (from hatch) (1.5.4)
Requirement already satisfied: tomli-w>=1.0 in /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages (from hatch) (1.0.0)
Requirement already satisfied: tomlkit>=0.11.1 in /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages (from hatch) (0.12.3)
Requirement already satisfied: userpath~=1.7 in /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages (from hatch) (1.9.1)
Requirement already satisfied: virtualenv>=20.16.2 in /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages (from hatch) (20.24.7)
Requirement already satisfied: editables>=0.3 in /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages (from hatchling>=1.14.0->hatch) (0.5)
Requirement already satisfied: pathspec>=0.10.1 in /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages (from hatchling>=1.14.0->hatch) (0.11.2)
Requirement already satisfied: pluggy>=1.0.0 in /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages (from hatchling>=1.14.0->hatch) (1.3.0)
Requirement already satisfied: tomli>=1.2.2 in /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages (from hatchling>=1.14.0->hatch) (2.0.1)
Requirement already satisfied: trove-classifiers in /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages (from hatchling>=1.14.0->hatch) (2023.11.22)
Requirement already satisfied: anyio in /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages (from httpx>=0.22.0->hatch) (4.1.0)
Requirement already satisfied: certifi in /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages (from httpx>=0.22.0->hatch) (2023.11.17)
Requirement already satisfied: httpcore==1.* in /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages (from httpx>=0.22.0->hatch) (1.0.2)
Requirement already satisfied: idna in /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages (from httpx>=0.22.0->hatch) (3.6)
Requirement already satisfied: sniffio in /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages (from httpx>=0.22.0->hatch) (1.3.0)
Requirement already satisfied: h11<0.15,>=0.13 in /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages (from httpcore==1.*->httpx>=0.22.0->hatch) (0.14.0)
Requirement already satisfied: jaraco.classes in /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages (from keyring>=23.5.0->hatch) (3.3.0)
Requirement already satisfied: importlib-metadata>=4.11.4 in /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages (from keyring>=23.5.0->hatch) (6.8.0)
Requirement already satisfied: ptyprocess>=0.5 in /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages (from pexpect~=4.8->hatch) (0.7.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages (from rich>=11.2.0->hatch) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages (from rich>=11.2.0->hatch) (2.17.2)
Requirement already satisfied: distlib<1,>=0.3.7 in /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages (from virtualenv>=20.16.2->hatch) (0.3.7)
Requirement already satisfied: filelock<4,>=3.12.2 in /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages (from virtualenv>=20.16.2->hatch) (3.13.1)
Requirement already satisfied: zipp>=0.5 in /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages (from importlib-metadata>=4.11.4->keyring>=23.5.0->hatch) (3.17.0)
Requirement already satisfied: mdurl~=0.1 in /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages (from markdown-it-py>=2.2.0->rich>=11.2.0->hatch) (0.1.2)
Requirement already satisfied: exceptiongroup>=1.0.2 in /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages (from anyio->httpx>=0.22.0->hatch) (1.2.0)
Requirement already satisfied: more-itertools in /Users/douglas.moore/.pyenv/versions/3.10.10/envs/ucx/lib/python3.10/site-packages (from jaraco.classes->keyring>=23.5.0->hatch) (10.1.0)
hatch env create
/Users/douglas.moore/development/ucx/.venv/bin/python
(ucx) douglas.moore@H4JD6Y7J50 ucx % databricks labs install .
Installing ucx in development mode from /Users/douglas.moore/development/ucx
Traceback (most recent call last):
  File "/Users/douglas.moore/development/ucx/src/databricks/labs/ucx/install.py", line 11, in <module>
    from databricks.labs.blueprint.entrypoint import get_logger
ModuleNotFoundError: No module named 'databricks.labs.blueprint'
Error: exit status 1
```
